// materialCatalog.js — Construction material catalog for NOVA 3D model
// Each entry has: visual properties, cost data, schedule data, assembly specs
// Costs are national averages ($/unit installed) — refined by NOVA Core over time
//
// CSI MasterFormat divisions covered:
//   03 — Concrete
//   04 — Masonry
//   05 — Metals
//   06 — Wood, Plastics, Composites
//   07 — Thermal & Moisture Protection
//   08 — Openings (Doors, Windows, Glazing)
//   09 — Finishes (Walls, Flooring, Ceiling, Painting)
//   10 — Specialties
//   11 — Equipment
//   12 — Furnishings
//   21 — Fire Suppression
//   22 — Plumbing
//   23 — HVAC
//   26 — Electrical
//   31 — Earthwork
//   32 — Exterior Improvements

export const MATERIAL_CATEGORIES = [
  { key: "concrete", label: "Concrete & Masonry" },
  { key: "metals", label: "Structural Metals" },
  { key: "wood-framing", label: "Wood & Composites" },
  { key: "exterior-cladding", label: "Exterior Cladding" },
  { key: "roofing", label: "Roofing" },
  { key: "waterproofing", label: "Waterproofing & Insulation" },
  { key: "doors-frames", label: "Doors & Frames" },
  { key: "glazing", label: "Glazing & Curtain Wall" },
  { key: "interior-wall", label: "Interior Wall Finish" },
  { key: "flooring", label: "Flooring" },
  { key: "ceiling", label: "Ceiling" },
  { key: "painting", label: "Painting & Coatings" },
  { key: "specialties", label: "Specialties" },
  { key: "plumbing-fixture", label: "Plumbing Fixtures" },
  { key: "fire-suppression", label: "Fire Suppression" },
  { key: "hvac", label: "HVAC" },
  { key: "electrical", label: "Electrical" },
  { key: "sitework", label: "Sitework & Earthwork" },
];

// ── 03 — Concrete & Masonry ────────────────────────────────────────
const CONCRETE = [
  {
    slug: "cast-concrete-wall",
    name: "Cast-in-Place Concrete Wall 8\"",
    manufacturer: "N/A",
    category: "concrete",
    visual: { color: "#BCBCBC", roughness: 0.95, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 12.00, laborPerUnit: 18.00, totalPerUnit: 30.00, unit: "SF" },
    schedule: { installRate: 50, crewSize: 6, leadTimeDays: 5 },
    assembly: { layers: [{ name: "8\" Cast Concrete", thickness: 8 }], rValue: 2, fireRating: "4-HR", stc: 55 },
    specSection: "03 30 00",
    ifcMaterial: "Cast-in-Place Concrete",
  },
  {
    slug: "cast-concrete-wall-12",
    name: "Cast-in-Place Concrete Wall 12\"",
    manufacturer: "N/A",
    category: "concrete",
    visual: { color: "#B0B0B0", roughness: 0.95, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 16.00, laborPerUnit: 22.00, totalPerUnit: 38.00, unit: "SF" },
    schedule: { installRate: 40, crewSize: 6, leadTimeDays: 7 },
    assembly: { layers: [{ name: "12\" Cast Concrete", thickness: 12 }], rValue: 3, fireRating: "4-HR", stc: 58 },
    specSection: "03 30 00",
    ifcMaterial: "Cast-in-Place Concrete",
  },
  {
    slug: "concrete-slab-4",
    name: "Concrete Slab on Grade 4\"",
    manufacturer: "N/A",
    category: "concrete",
    visual: { color: "#C0C0C0", roughness: 0.8, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 4.50, totalPerUnit: 8.00, unit: "SF" },
    schedule: { installRate: 800, crewSize: 6, leadTimeDays: 3 },
    assembly: { layers: [{ name: "4\" Concrete Slab", thickness: 4 }, { name: "6mil Vapor Barrier", thickness: 0.006 }, { name: "4\" Gravel Base", thickness: 4 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "03 30 00",
    ifcMaterial: "Concrete Slab on Grade",
  },
  {
    slug: "concrete-slab-6",
    name: "Concrete Slab on Grade 6\"",
    manufacturer: "N/A",
    category: "concrete",
    visual: { color: "#C0C0C0", roughness: 0.8, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 5.00, laborPerUnit: 5.50, totalPerUnit: 10.50, unit: "SF" },
    schedule: { installRate: 700, crewSize: 6, leadTimeDays: 3 },
    assembly: { layers: [{ name: "6\" Concrete Slab", thickness: 6 }, { name: "6mil Vapor Barrier", thickness: 0.006 }, { name: "4\" Gravel Base", thickness: 4 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "03 30 00",
    ifcMaterial: "Concrete Slab on Grade",
  },
  {
    slug: "concrete-footing",
    name: "Continuous Footing 24\" × 12\"",
    manufacturer: "N/A",
    category: "concrete",
    visual: { color: "#A8A8A8", roughness: 0.95, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 18.00, laborPerUnit: 14.00, totalPerUnit: 32.00, unit: "LF" },
    schedule: { installRate: 80, crewSize: 4, leadTimeDays: 3 },
    assembly: { layers: [{ name: "24\"×12\" Concrete Footing w/ #5 Rebar", thickness: 12 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "03 30 00",
    ifcMaterial: "Concrete Footing",
  },
  {
    slug: "precast-concrete-panel",
    name: "Precast Concrete Panel 6\"",
    manufacturer: "Various",
    category: "concrete",
    visual: { color: "#D0CCC4", roughness: 0.7, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 22.00, laborPerUnit: 12.00, totalPerUnit: 34.00, unit: "SF" },
    schedule: { installRate: 120, crewSize: 5, leadTimeDays: 42 },
    assembly: { layers: [{ name: "6\" Precast Concrete Panel", thickness: 6 }], rValue: 2, fireRating: "3-HR", stc: 52 },
    specSection: "03 40 00",
    ifcMaterial: "Precast Concrete Panel",
  },
  {
    slug: "cmu-8-block",
    name: "CMU 8\" Block — Painted",
    manufacturer: "Various",
    category: "concrete",
    visual: { color: "#A0A0A0", roughness: 0.9, metalness: 0, pattern: "block", patternScale: 8 },
    cost: { materialPerUnit: 6.50, laborPerUnit: 10.50, totalPerUnit: 17.00, unit: "SF" },
    schedule: { installRate: 100, crewSize: 4, leadTimeDays: 10 },
    assembly: { layers: [{ name: "8\" CMU Block", thickness: 7.625 }], rValue: 2, fireRating: "2-HR", stc: 48 },
    specSection: "04 22 00",
    ifcMaterial: "Concrete Masonry Unit",
  },
  {
    slug: "cmu-12-grouted",
    name: "CMU 12\" Grouted & Reinforced",
    manufacturer: "Various",
    category: "concrete",
    visual: { color: "#A0A0A0", roughness: 0.9, metalness: 0, pattern: "block", patternScale: 8 },
    cost: { materialPerUnit: 9.00, laborPerUnit: 13.00, totalPerUnit: 22.00, unit: "SF" },
    schedule: { installRate: 80, crewSize: 4, leadTimeDays: 10 },
    assembly: { layers: [{ name: "12\" CMU Grouted", thickness: 11.625 }], rValue: 3, fireRating: "4-HR", stc: 55 },
    specSection: "04 22 00",
    ifcMaterial: "Concrete Masonry Unit Grouted",
  },
  {
    slug: "split-face-cmu",
    name: "Split Face CMU 8\"",
    manufacturer: "Various",
    category: "concrete",
    visual: { color: "#B5A89A", roughness: 0.95, metalness: 0, pattern: "block", patternScale: 8 },
    cost: { materialPerUnit: 8.50, laborPerUnit: 12.00, totalPerUnit: 20.50, unit: "SF" },
    schedule: { installRate: 90, crewSize: 4, leadTimeDays: 14 },
    assembly: { layers: [{ name: "8\" Split Face CMU", thickness: 7.625 }], rValue: 2, fireRating: "2-HR", stc: 48 },
    specSection: "04 22 00",
    ifcMaterial: "Split Face CMU",
  },
  {
    slug: "polished-concrete",
    name: "Polished Concrete Floor",
    manufacturer: "N/A",
    category: "concrete",
    visual: { color: "#BCBCBC", roughness: 0.3, metalness: 0.1, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.00, laborPerUnit: 4.00, totalPerUnit: 6.00, unit: "SF" },
    schedule: { installRate: 500, crewSize: 3, leadTimeDays: 3 },
    assembly: { layers: [{ name: "Polished Concrete Slab", thickness: 0.25 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "03 35 00",
    ifcMaterial: "Polished Concrete",
  },
];

// ── 05 — Metals ────────────────────────────────────────────────────
const METALS = [
  {
    slug: "w-beam-structural",
    name: "Structural Steel W-Beam",
    manufacturer: "Various",
    category: "metals",
    visual: { color: "#6B6B6B", roughness: 0.4, metalness: 0.9, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3800, laborPerUnit: 2200, totalPerUnit: 6000, unit: "TN" },
    schedule: { installRate: 3, crewSize: 5, leadTimeDays: 56 },
    assembly: { layers: [{ name: "W-Shape Steel Beam", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 12 00",
    ifcMaterial: "Structural Steel",
  },
  {
    slug: "hss-tube-steel",
    name: "HSS Tube Steel Column",
    manufacturer: "Various",
    category: "metals",
    visual: { color: "#707070", roughness: 0.35, metalness: 0.9, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 4200, laborPerUnit: 2400, totalPerUnit: 6600, unit: "TN" },
    schedule: { installRate: 3, crewSize: 5, leadTimeDays: 56 },
    assembly: { layers: [{ name: "HSS Tube Steel", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 12 00",
    ifcMaterial: "HSS Tube Steel",
  },
  {
    slug: "steel-deck-15",
    name: "Steel Roof/Floor Deck 1.5\" 20ga",
    manufacturer: "Vulcraft",
    category: "metals",
    visual: { color: "#808080", roughness: 0.3, metalness: 0.85, pattern: "vertical-rib", patternScale: 6 },
    cost: { materialPerUnit: 2.80, laborPerUnit: 2.20, totalPerUnit: 5.00, unit: "SF" },
    schedule: { installRate: 600, crewSize: 4, leadTimeDays: 28 },
    assembly: { layers: [{ name: "1.5\" 20ga Steel Deck", thickness: 1.5 }], rValue: 0, fireRating: "1-HR", stc: 30 },
    specSection: "05 31 00",
    ifcMaterial: "Steel Deck",
  },
  {
    slug: "steel-deck-3",
    name: "Steel Composite Deck 3\" 18ga",
    manufacturer: "Vulcraft",
    category: "metals",
    visual: { color: "#808080", roughness: 0.3, metalness: 0.85, pattern: "vertical-rib", patternScale: 6 },
    cost: { materialPerUnit: 4.50, laborPerUnit: 3.00, totalPerUnit: 7.50, unit: "SF" },
    schedule: { installRate: 500, crewSize: 4, leadTimeDays: 28 },
    assembly: { layers: [{ name: "3\" 18ga Composite Steel Deck", thickness: 3 }], rValue: 0, fireRating: "2-HR", stc: 35 },
    specSection: "05 31 00",
    ifcMaterial: "Composite Steel Deck",
  },
  {
    slug: "steel-joist",
    name: "Open Web Steel Joist",
    manufacturer: "Vulcraft",
    category: "metals",
    visual: { color: "#6B6B6B", roughness: 0.4, metalness: 0.9, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 8.50, laborPerUnit: 5.50, totalPerUnit: 14.00, unit: "SF" },
    schedule: { installRate: 400, crewSize: 5, leadTimeDays: 42 },
    assembly: { layers: [{ name: "Open Web Steel Joist", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 21 00",
    ifcMaterial: "Steel Joist",
  },
  {
    slug: "metal-stud-358",
    name: "Metal Stud 3-5/8\" 20ga",
    manufacturer: "ClarkDietrich",
    category: "metals",
    visual: { color: "#C0C0C0", roughness: 0.3, metalness: 0.8, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 0.85, laborPerUnit: 1.15, totalPerUnit: 2.00, unit: "LF" },
    schedule: { installRate: 800, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "3-5/8\" 20ga Steel Stud", thickness: 3.625 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 41 00",
    ifcMaterial: "Steel Stud Framing",
  },
  {
    slug: "metal-stud-6",
    name: "Metal Stud 6\" 20ga",
    manufacturer: "ClarkDietrich",
    category: "metals",
    visual: { color: "#C0C0C0", roughness: 0.3, metalness: 0.8, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1.20, laborPerUnit: 1.30, totalPerUnit: 2.50, unit: "LF" },
    schedule: { installRate: 700, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "6\" 20ga Steel Stud", thickness: 6 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 41 00",
    ifcMaterial: "Steel Stud Framing",
  },
  {
    slug: "misc-steel",
    name: "Miscellaneous Steel (lintels, angles, plates)",
    manufacturer: "Various",
    category: "metals",
    visual: { color: "#6B6B6B", roughness: 0.5, metalness: 0.85, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 4500, laborPerUnit: 3000, totalPerUnit: 7500, unit: "TN" },
    schedule: { installRate: 2, crewSize: 3, leadTimeDays: 28 },
    assembly: { layers: [{ name: "Misc Steel", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 50 00",
    ifcMaterial: "Miscellaneous Steel",
  },
  {
    slug: "steel-handrail",
    name: "Steel Pipe Handrail 1.5\" dia",
    manufacturer: "Various",
    category: "metals",
    visual: { color: "#505050", roughness: 0.3, metalness: 0.9, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 35.00, laborPerUnit: 25.00, totalPerUnit: 60.00, unit: "LF" },
    schedule: { installRate: 40, crewSize: 2, leadTimeDays: 21 },
    assembly: { layers: [{ name: "1.5\" Steel Pipe Rail", thickness: 1.5 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 52 00",
    ifcMaterial: "Steel Handrail",
  },
  {
    slug: "aluminum-railing",
    name: "Aluminum Railing System",
    manufacturer: "Various",
    category: "metals",
    visual: { color: "#C8C8C8", roughness: 0.2, metalness: 0.85, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 55.00, laborPerUnit: 30.00, totalPerUnit: 85.00, unit: "LF" },
    schedule: { installRate: 30, crewSize: 2, leadTimeDays: 28 },
    assembly: { layers: [{ name: "Aluminum Rail System", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "05 73 00",
    ifcMaterial: "Aluminum Railing",
  },
];

// ── 06 — Wood & Composites ─────────────────────────────────────────
const WOOD_FRAMING = [
  {
    slug: "wood-stud-2x4",
    name: "Wood Stud Wall 2×4 16\" O.C.",
    manufacturer: "Various",
    category: "wood-framing",
    visual: { color: "#D4A574", roughness: 0.8, metalness: 0, pattern: "wood-plank", patternScale: 1 },
    cost: { materialPerUnit: 1.80, laborPerUnit: 3.20, totalPerUnit: 5.00, unit: "SF" },
    schedule: { installRate: 300, crewSize: 4, leadTimeDays: 5 },
    assembly: { layers: [{ name: "2×4 SPF Stud 16\" O.C.", thickness: 3.5 }], rValue: 0, fireRating: "0-HR", stc: 0 },
    specSection: "06 11 00",
    ifcMaterial: "Wood Framing",
  },
  {
    slug: "wood-stud-2x6",
    name: "Wood Stud Wall 2×6 16\" O.C.",
    manufacturer: "Various",
    category: "wood-framing",
    visual: { color: "#D4A574", roughness: 0.8, metalness: 0, pattern: "wood-plank", patternScale: 1 },
    cost: { materialPerUnit: 2.40, laborPerUnit: 3.50, totalPerUnit: 5.90, unit: "SF" },
    schedule: { installRate: 280, crewSize: 4, leadTimeDays: 5 },
    assembly: { layers: [{ name: "2×6 SPF Stud 16\" O.C.", thickness: 5.5 }], rValue: 0, fireRating: "0-HR", stc: 0 },
    specSection: "06 11 00",
    ifcMaterial: "Wood Framing",
  },
  {
    slug: "lvl-beam",
    name: "LVL Beam 1-3/4\" × 11-7/8\"",
    manufacturer: "Weyerhaeuser",
    category: "wood-framing",
    visual: { color: "#C49A6C", roughness: 0.6, metalness: 0, pattern: "wood-plank", patternScale: 1 },
    cost: { materialPerUnit: 8.50, laborPerUnit: 4.50, totalPerUnit: 13.00, unit: "LF" },
    schedule: { installRate: 60, crewSize: 3, leadTimeDays: 14 },
    assembly: { layers: [{ name: "LVL Beam", thickness: 1.75 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "06 17 00",
    ifcMaterial: "Laminated Veneer Lumber",
  },
  {
    slug: "tji-joist",
    name: "TJI Floor Joist 11-7/8\" 16\" O.C.",
    manufacturer: "Weyerhaeuser",
    category: "wood-framing",
    visual: { color: "#C49A6C", roughness: 0.6, metalness: 0, pattern: "wood-plank", patternScale: 1 },
    cost: { materialPerUnit: 3.00, laborPerUnit: 2.50, totalPerUnit: 5.50, unit: "SF" },
    schedule: { installRate: 400, crewSize: 4, leadTimeDays: 14 },
    assembly: { layers: [{ name: "TJI I-Joist 11-7/8\"", thickness: 11.875 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "06 17 00",
    ifcMaterial: "Engineered Wood Joist",
  },
  {
    slug: "glulam-beam",
    name: "Glulam Beam 5-1/8\" × 12\"",
    manufacturer: "Various",
    category: "wood-framing",
    visual: { color: "#B8905C", roughness: 0.5, metalness: 0, pattern: "wood-plank", patternScale: 1 },
    cost: { materialPerUnit: 18.00, laborPerUnit: 8.00, totalPerUnit: 26.00, unit: "LF" },
    schedule: { installRate: 30, crewSize: 4, leadTimeDays: 21 },
    assembly: { layers: [{ name: "Glulam Beam", thickness: 5.125 }], rValue: 0, fireRating: "1-HR", stc: 0 },
    specSection: "06 18 00",
    ifcMaterial: "Glued Laminated Timber",
  },
  {
    slug: "plywood-sheathing",
    name: "Plywood Sheathing 1/2\" CDX",
    manufacturer: "Various",
    category: "wood-framing",
    visual: { color: "#C4A882", roughness: 0.7, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1.50, laborPerUnit: 1.25, totalPerUnit: 2.75, unit: "SF" },
    schedule: { installRate: 600, crewSize: 3, leadTimeDays: 3 },
    assembly: { layers: [{ name: "1/2\" CDX Plywood", thickness: 0.5 }], rValue: 0.5, fireRating: "", stc: 0 },
    specSection: "06 16 00",
    ifcMaterial: "Plywood Sheathing",
  },
  {
    slug: "osb-sheathing",
    name: "OSB Sheathing 7/16\"",
    manufacturer: "Various",
    category: "wood-framing",
    visual: { color: "#C9A870", roughness: 0.75, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1.10, laborPerUnit: 1.25, totalPerUnit: 2.35, unit: "SF" },
    schedule: { installRate: 650, crewSize: 3, leadTimeDays: 3 },
    assembly: { layers: [{ name: "7/16\" OSB", thickness: 0.4375 }], rValue: 0.5, fireRating: "", stc: 0 },
    specSection: "06 16 00",
    ifcMaterial: "OSB Sheathing",
  },
];

// ── 07 — Exterior Cladding ─────────────────────────────────────────
const EXTERIOR_CLADDING = [
  {
    slug: "hardie-lap-siding",
    name: "James Hardie Lap Siding",
    manufacturer: "James Hardie",
    category: "exterior-cladding",
    visual: { color: "#E8DCC8", roughness: 0.6, metalness: 0, pattern: "horizontal-lap", patternScale: 7 },
    cost: { materialPerUnit: 4.25, laborPerUnit: 6.50, totalPerUnit: 10.75, unit: "SF" },
    schedule: { installRate: 200, crewSize: 3, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Hardie Plank 5/16\"", thickness: 0.3125 }, { name: "Tyvek HomeWrap", thickness: 0.01 }, { name: "OSB Sheathing 7/16\"", thickness: 0.4375 }], rValue: 4, fireRating: "1-HR", stc: 38 },
    specSection: "07 46 23",
    ifcMaterial: "Fiber Cement Lap Siding",
  },
  {
    slug: "hardie-panel",
    name: "James Hardie Panel 4' × 8'",
    manufacturer: "James Hardie",
    category: "exterior-cladding",
    visual: { color: "#E0D8C8", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 5.00, laborPerUnit: 5.50, totalPerUnit: 10.50, unit: "SF" },
    schedule: { installRate: 250, crewSize: 3, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Hardie Panel 5/16\"", thickness: 0.3125 }, { name: "Tyvek HomeWrap", thickness: 0.01 }, { name: "OSB Sheathing 7/16\"", thickness: 0.4375 }], rValue: 4, fireRating: "1-HR", stc: 38 },
    specSection: "07 46 23",
    ifcMaterial: "Fiber Cement Panel",
  },
  {
    slug: "cedar-bevel-siding",
    name: "Western Red Cedar Bevel Siding",
    manufacturer: "Various",
    category: "exterior-cladding",
    visual: { color: "#C4956A", roughness: 0.7, metalness: 0, pattern: "horizontal-lap", patternScale: 8 },
    cost: { materialPerUnit: 8.50, laborPerUnit: 8.00, totalPerUnit: 16.50, unit: "SF" },
    schedule: { installRate: 160, crewSize: 3, leadTimeDays: 21 },
    assembly: { layers: [{ name: "3/4\" WRC Bevel", thickness: 0.75 }, { name: "Tyvek HomeWrap", thickness: 0.01 }, { name: "OSB Sheathing 7/16\"", thickness: 0.4375 }], rValue: 5, fireRating: "0-HR", stc: 36 },
    specSection: "07 46 13",
    ifcMaterial: "Western Red Cedar Siding",
  },
  {
    slug: "vinyl-siding",
    name: "Vinyl Siding Double 4\"",
    manufacturer: "CertainTeed",
    category: "exterior-cladding",
    visual: { color: "#D4D0C8", roughness: 0.4, metalness: 0, pattern: "horizontal-lap", patternScale: 4 },
    cost: { materialPerUnit: 2.50, laborPerUnit: 3.50, totalPerUnit: 6.00, unit: "SF" },
    schedule: { installRate: 300, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "Vinyl Siding .044\"", thickness: 0.044 }, { name: "Fanfold Insulation", thickness: 0.25 }, { name: "OSB Sheathing 7/16\"", thickness: 0.4375 }], rValue: 3, fireRating: "0-HR", stc: 32 },
    specSection: "07 46 43",
    ifcMaterial: "Vinyl Siding",
  },
  {
    slug: "metal-panel-ribbed",
    name: "Metal Wall Panel Ribbed 24ga",
    manufacturer: "MBCI",
    category: "exterior-cladding",
    visual: { color: "#C0C0C0", roughness: 0.2, metalness: 0.8, pattern: "vertical-rib", patternScale: 12 },
    cost: { materialPerUnit: 6.00, laborPerUnit: 5.00, totalPerUnit: 11.00, unit: "SF" },
    schedule: { installRate: 250, crewSize: 4, leadTimeDays: 21 },
    assembly: { layers: [{ name: "24ga Steel Panel", thickness: 0.025 }, { name: "Rigid Insulation 2\"", thickness: 2 }, { name: "Steel Girt", thickness: 1.5 }], rValue: 13, fireRating: "1-HR", stc: 35 },
    specSection: "07 42 13",
    ifcMaterial: "Metal Wall Panel",
  },
  {
    slug: "metal-panel-flat",
    name: "Metal Wall Panel Flat Lock 22ga",
    manufacturer: "PAC-CLAD",
    category: "exterior-cladding",
    visual: { color: "#A0A0A0", roughness: 0.15, metalness: 0.85, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 10.00, laborPerUnit: 8.00, totalPerUnit: 18.00, unit: "SF" },
    schedule: { installRate: 150, crewSize: 4, leadTimeDays: 28 },
    assembly: { layers: [{ name: "22ga Flat Lock Panel", thickness: 0.03 }, { name: "Rigid Insulation 2\"", thickness: 2 }], rValue: 13, fireRating: "1-HR", stc: 35 },
    specSection: "07 42 13",
    ifcMaterial: "Metal Wall Panel",
  },
  {
    slug: "eifs-stucco",
    name: "EIFS / Synthetic Stucco",
    manufacturer: "Dryvit",
    category: "exterior-cladding",
    visual: { color: "#F5F0E8", roughness: 0.7, metalness: 0, pattern: "stucco", patternScale: 1 },
    cost: { materialPerUnit: 7.50, laborPerUnit: 9.50, totalPerUnit: 17.00, unit: "SF" },
    schedule: { installRate: 120, crewSize: 4, leadTimeDays: 14 },
    assembly: { layers: [{ name: "EIFS Finish Coat", thickness: 0.125 }, { name: "EPS Insulation 2\"", thickness: 2 }, { name: "Base Coat + Mesh", thickness: 0.125 }], rValue: 11, fireRating: "1-HR", stc: 40 },
    specSection: "07 24 13",
    ifcMaterial: "EIFS",
  },
  {
    slug: "3-coat-stucco",
    name: "3-Coat Portland Cement Stucco",
    manufacturer: "Various",
    category: "exterior-cladding",
    visual: { color: "#E8E0D0", roughness: 0.75, metalness: 0, pattern: "stucco", patternScale: 1 },
    cost: { materialPerUnit: 6.00, laborPerUnit: 10.00, totalPerUnit: 16.00, unit: "SF" },
    schedule: { installRate: 100, crewSize: 4, leadTimeDays: 14 },
    assembly: { layers: [{ name: "3-Coat Stucco 7/8\"", thickness: 0.875 }, { name: "Metal Lath", thickness: 0.125 }], rValue: 1, fireRating: "1-HR", stc: 42 },
    specSection: "07 24 00",
    ifcMaterial: "Portland Cement Stucco",
  },
  {
    slug: "brick-veneer",
    name: "Standard Brick Veneer",
    manufacturer: "Various",
    category: "exterior-cladding",
    visual: { color: "#B5651D", roughness: 0.8, metalness: 0, pattern: "brick", patternScale: 2.67 },
    cost: { materialPerUnit: 8.00, laborPerUnit: 14.00, totalPerUnit: 22.00, unit: "SF" },
    schedule: { installRate: 80, crewSize: 4, leadTimeDays: 21 },
    assembly: { layers: [{ name: "Standard Brick 3-5/8\"", thickness: 3.625 }, { name: "1\" Air Space", thickness: 1 }, { name: "Building Wrap", thickness: 0.01 }], rValue: 5, fireRating: "2-HR", stc: 45 },
    specSection: "04 21 13",
    ifcMaterial: "Brick Veneer",
  },
  {
    slug: "thin-brick",
    name: "Thin Brick Veneer Adhered",
    manufacturer: "Various",
    category: "exterior-cladding",
    visual: { color: "#B06030", roughness: 0.8, metalness: 0, pattern: "brick", patternScale: 2.67 },
    cost: { materialPerUnit: 10.00, laborPerUnit: 10.00, totalPerUnit: 20.00, unit: "SF" },
    schedule: { installRate: 60, crewSize: 3, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Thin Brick 1/2\"", thickness: 0.5 }, { name: "Adhesive", thickness: 0.125 }], rValue: 1, fireRating: "1-HR", stc: 40 },
    specSection: "04 21 13.13",
    ifcMaterial: "Thin Brick Veneer",
  },
  {
    slug: "stone-veneer-natural",
    name: "Natural Stone Veneer 1\"",
    manufacturer: "Various",
    category: "exterior-cladding",
    visual: { color: "#C8B898", roughness: 0.85, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 18.00, laborPerUnit: 20.00, totalPerUnit: 38.00, unit: "SF" },
    schedule: { installRate: 40, crewSize: 3, leadTimeDays: 28 },
    assembly: { layers: [{ name: "1\" Natural Stone Veneer", thickness: 1 }, { name: "Mortar Bed", thickness: 0.5 }], rValue: 1, fireRating: "2-HR", stc: 48 },
    specSection: "04 42 00",
    ifcMaterial: "Natural Stone Veneer",
  },
  {
    slug: "acm-panel",
    name: "ACM (Aluminum Composite) Panel",
    manufacturer: "Alucobond",
    category: "exterior-cladding",
    visual: { color: "#606060", roughness: 0.15, metalness: 0.8, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 18.00, laborPerUnit: 14.00, totalPerUnit: 32.00, unit: "SF" },
    schedule: { installRate: 80, crewSize: 4, leadTimeDays: 42 },
    assembly: { layers: [{ name: "4mm ACM Panel", thickness: 0.16 }, { name: "Aluminum Sub-frame", thickness: 2 }], rValue: 0, fireRating: "0-HR", stc: 28 },
    specSection: "07 42 43",
    ifcMaterial: "Aluminum Composite Panel",
  },
];

// ── 07 — Roofing ───────────────────────────────────────────────────
const ROOFING = [
  {
    slug: "tpo-60mil",
    name: "TPO Membrane 60mil",
    manufacturer: "Carlisle",
    category: "roofing",
    visual: { color: "#E8E8E8", roughness: 0.3, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 4.75, totalPerUnit: 8.25, unit: "SF" },
    schedule: { installRate: 400, crewSize: 5, leadTimeDays: 14 },
    assembly: { layers: [{ name: "TPO Membrane 60mil", thickness: 0.06 }, { name: "Polyiso Insulation 3\"", thickness: 3 }, { name: "Vapor Barrier", thickness: 0.01 }], rValue: 18, fireRating: "A", stc: 0 },
    specSection: "07 54 23",
    ifcMaterial: "TPO Roofing Membrane",
  },
  {
    slug: "tpo-80mil",
    name: "TPO Membrane 80mil",
    manufacturer: "Carlisle",
    category: "roofing",
    visual: { color: "#E8E8E8", roughness: 0.3, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 4.50, laborPerUnit: 5.00, totalPerUnit: 9.50, unit: "SF" },
    schedule: { installRate: 380, crewSize: 5, leadTimeDays: 14 },
    assembly: { layers: [{ name: "TPO Membrane 80mil", thickness: 0.08 }, { name: "Polyiso Insulation 3\"", thickness: 3 }, { name: "Vapor Barrier", thickness: 0.01 }], rValue: 18, fireRating: "A", stc: 0 },
    specSection: "07 54 23",
    ifcMaterial: "TPO Roofing Membrane",
  },
  {
    slug: "epdm-60mil",
    name: "EPDM Membrane 60mil",
    manufacturer: "Firestone",
    category: "roofing",
    visual: { color: "#2D2D2D", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.00, laborPerUnit: 4.00, totalPerUnit: 7.00, unit: "SF" },
    schedule: { installRate: 450, crewSize: 5, leadTimeDays: 10 },
    assembly: { layers: [{ name: "EPDM Membrane 60mil", thickness: 0.06 }, { name: "Polyiso Insulation 3\"", thickness: 3 }, { name: "Vapor Barrier", thickness: 0.01 }], rValue: 18, fireRating: "A", stc: 0 },
    specSection: "07 53 23",
    ifcMaterial: "EPDM Roofing Membrane",
  },
  {
    slug: "pvc-membrane-60",
    name: "PVC Membrane 60mil",
    manufacturer: "Sarnafil",
    category: "roofing",
    visual: { color: "#E0E0E0", roughness: 0.3, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 5.00, laborPerUnit: 5.50, totalPerUnit: 10.50, unit: "SF" },
    schedule: { installRate: 350, crewSize: 5, leadTimeDays: 14 },
    assembly: { layers: [{ name: "PVC Membrane 60mil", thickness: 0.06 }, { name: "Polyiso Insulation 3\"", thickness: 3 }, { name: "Vapor Barrier", thickness: 0.01 }], rValue: 18, fireRating: "A", stc: 0 },
    specSection: "07 54 23",
    ifcMaterial: "PVC Roofing Membrane",
  },
  {
    slug: "built-up-roof",
    name: "Built-Up Roof 4-Ply",
    manufacturer: "Various",
    category: "roofing",
    visual: { color: "#4A4A4A", roughness: 0.7, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 4.00, laborPerUnit: 5.00, totalPerUnit: 9.00, unit: "SF" },
    schedule: { installRate: 300, crewSize: 5, leadTimeDays: 10 },
    assembly: { layers: [{ name: "Cap Sheet", thickness: 0.125 }, { name: "4-Ply Asphalt + Felt", thickness: 0.5 }, { name: "Polyiso Insulation 3\"", thickness: 3 }], rValue: 18, fireRating: "A", stc: 0 },
    specSection: "07 51 00",
    ifcMaterial: "Built-Up Roofing",
  },
  {
    slug: "standing-seam-metal",
    name: "Standing Seam Metal Roof 24ga",
    manufacturer: "Berridge",
    category: "roofing",
    visual: { color: "#8B8B8B", roughness: 0.2, metalness: 0.7, pattern: "vertical-rib", patternScale: 16 },
    cost: { materialPerUnit: 8.00, laborPerUnit: 7.00, totalPerUnit: 15.00, unit: "SF" },
    schedule: { installRate: 150, crewSize: 4, leadTimeDays: 28 },
    assembly: { layers: [{ name: "24ga Steel Panel", thickness: 0.025 }, { name: "Underlayment", thickness: 0.0625 }, { name: "Rigid Insulation 2\"", thickness: 2 }], rValue: 13, fireRating: "A", stc: 30 },
    specSection: "07 41 13",
    ifcMaterial: "Standing Seam Metal Roof",
  },
  {
    slug: "asphalt-shingle",
    name: "Architectural Asphalt Shingle",
    manufacturer: "GAF",
    category: "roofing",
    visual: { color: "#4A4A4A", roughness: 0.8, metalness: 0, pattern: "shingle", patternScale: 5 },
    cost: { materialPerUnit: 2.25, laborPerUnit: 3.75, totalPerUnit: 6.00, unit: "SF" },
    schedule: { installRate: 500, crewSize: 5, leadTimeDays: 7 },
    assembly: { layers: [{ name: "Architectural Shingle", thickness: 0.25 }, { name: "Underlayment", thickness: 0.0625 }, { name: "Plywood Sheathing 1/2\"", thickness: 0.5 }], rValue: 1, fireRating: "A", stc: 0 },
    specSection: "07 31 13",
    ifcMaterial: "Asphalt Shingle",
  },
  {
    slug: "mod-bit-roof",
    name: "Modified Bitumen SBS 2-Ply",
    manufacturer: "Various",
    category: "roofing",
    visual: { color: "#3A3A3A", roughness: 0.6, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 4.50, totalPerUnit: 8.00, unit: "SF" },
    schedule: { installRate: 350, crewSize: 5, leadTimeDays: 10 },
    assembly: { layers: [{ name: "SBS Cap Sheet", thickness: 0.15 }, { name: "SBS Base Sheet", thickness: 0.15 }, { name: "Polyiso 3\"", thickness: 3 }], rValue: 18, fireRating: "A", stc: 0 },
    specSection: "07 52 00",
    ifcMaterial: "Modified Bitumen Roofing",
  },
];

// ── 07 — Waterproofing & Insulation ────────────────────────────────
const WATERPROOFING = [
  {
    slug: "polyiso-board-2",
    name: "Polyiso Rigid Insulation 2\"",
    manufacturer: "Various",
    category: "waterproofing",
    visual: { color: "#F0E0A0", roughness: 0.6, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1.20, laborPerUnit: 0.80, totalPerUnit: 2.00, unit: "SF" },
    schedule: { installRate: 800, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "2\" Polyiso Board", thickness: 2 }], rValue: 13, fireRating: "Class A", stc: 0 },
    specSection: "07 21 16",
    ifcMaterial: "Polyisocyanurate Insulation",
  },
  {
    slug: "xps-board-2",
    name: "XPS Rigid Insulation 2\"",
    manufacturer: "Dow",
    category: "waterproofing",
    visual: { color: "#B0D0F0", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1.00, laborPerUnit: 0.80, totalPerUnit: 1.80, unit: "SF" },
    schedule: { installRate: 800, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "2\" XPS Board", thickness: 2 }], rValue: 10, fireRating: "Class A", stc: 0 },
    specSection: "07 21 13",
    ifcMaterial: "Extruded Polystyrene Insulation",
  },
  {
    slug: "spray-foam-closed",
    name: "Closed Cell Spray Foam 2\"",
    manufacturer: "Various",
    category: "waterproofing",
    visual: { color: "#F5F0D0", roughness: 0.8, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.00, laborPerUnit: 2.50, totalPerUnit: 4.50, unit: "SF" },
    schedule: { installRate: 500, crewSize: 2, leadTimeDays: 3 },
    assembly: { layers: [{ name: "2\" Closed Cell SPF", thickness: 2 }], rValue: 14, fireRating: "Class A", stc: 0 },
    specSection: "07 21 29",
    ifcMaterial: "Spray Polyurethane Foam",
  },
  {
    slug: "batt-insulation-r19",
    name: "Fiberglass Batt R-19 6-1/4\"",
    manufacturer: "Owens Corning",
    category: "waterproofing",
    visual: { color: "#FFD0D0", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 0.65, laborPerUnit: 0.55, totalPerUnit: 1.20, unit: "SF" },
    schedule: { installRate: 800, crewSize: 2, leadTimeDays: 3 },
    assembly: { layers: [{ name: "R-19 Fiberglass Batt", thickness: 6.25 }], rValue: 19, fireRating: "Class A", stc: 0 },
    specSection: "07 21 16",
    ifcMaterial: "Fiberglass Batt Insulation",
  },
  {
    slug: "mineral-wool-batt",
    name: "Mineral Wool Batt R-15 3-1/2\"",
    manufacturer: "Rockwool",
    category: "waterproofing",
    visual: { color: "#A09060", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1.10, laborPerUnit: 0.60, totalPerUnit: 1.70, unit: "SF" },
    schedule: { installRate: 700, crewSize: 2, leadTimeDays: 5 },
    assembly: { layers: [{ name: "3-1/2\" Mineral Wool Batt", thickness: 3.5 }], rValue: 15, fireRating: "Class A", stc: 45 },
    specSection: "07 21 16",
    ifcMaterial: "Mineral Wool Insulation",
  },
  {
    slug: "fluid-applied-membrane",
    name: "Fluid-Applied Air/Water Barrier",
    manufacturer: "Henry",
    category: "waterproofing",
    visual: { color: "#303030", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.50, laborPerUnit: 2.00, totalPerUnit: 4.50, unit: "SF" },
    schedule: { installRate: 400, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "Fluid-Applied Membrane 60mil", thickness: 0.06 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "07 27 00",
    ifcMaterial: "Fluid-Applied Membrane",
  },
  {
    slug: "sheet-membrane-wp",
    name: "Sheet Waterproofing Membrane (Below Grade)",
    manufacturer: "Carlisle",
    category: "waterproofing",
    visual: { color: "#202020", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.00, laborPerUnit: 2.50, totalPerUnit: 5.50, unit: "SF" },
    schedule: { installRate: 350, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "60mil Sheet Membrane", thickness: 0.06 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "07 11 00",
    ifcMaterial: "Sheet Waterproofing",
  },
  {
    slug: "building-wrap",
    name: "Tyvek HomeWrap (Building Wrap)",
    manufacturer: "DuPont",
    category: "waterproofing",
    visual: { color: "#F0F0F0", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 0.20, laborPerUnit: 0.30, totalPerUnit: 0.50, unit: "SF" },
    schedule: { installRate: 1200, crewSize: 2, leadTimeDays: 3 },
    assembly: { layers: [{ name: "Tyvek HomeWrap", thickness: 0.01 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "07 25 00",
    ifcMaterial: "Weather Resistant Barrier",
  },
];

// ── 08 — Doors & Frames ───────────────────────────────────────────
const DOORS_FRAMES = [
  {
    slug: "hm-door-frame-36",
    name: "HM Door & Frame 3'-0\" × 7'-0\" (Painted)",
    manufacturer: "Various",
    category: "doors-frames",
    visual: { color: "#808080", roughness: 0.5, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 550, laborPerUnit: 250, totalPerUnit: 800, unit: "EA" },
    schedule: { installRate: 6, crewSize: 2, leadTimeDays: 21 },
    assembly: { layers: [{ name: "18ga HM Door", thickness: 1.75 }, { name: "16ga HM Frame", thickness: 0 }], rValue: 0, fireRating: "1-HR", stc: 35 },
    specSection: "08 11 13",
    ifcMaterial: "Hollow Metal Door",
  },
  {
    slug: "hm-door-frame-36-90",
    name: "HM Door & Frame 3'-0\" × 7'-0\" (90-min FRR)",
    manufacturer: "Various",
    category: "doors-frames",
    visual: { color: "#808080", roughness: 0.5, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 750, laborPerUnit: 280, totalPerUnit: 1030, unit: "EA" },
    schedule: { installRate: 5, crewSize: 2, leadTimeDays: 28 },
    assembly: { layers: [{ name: "18ga HM Door (90-min Label)", thickness: 1.75 }, { name: "16ga HM Frame", thickness: 0 }], rValue: 0, fireRating: "90-MIN", stc: 40 },
    specSection: "08 11 13",
    ifcMaterial: "Hollow Metal Door (Fire Rated)",
  },
  {
    slug: "wood-door-flush",
    name: "Solid Core Wood Door 3'-0\" × 7'-0\"",
    manufacturer: "Various",
    category: "doors-frames",
    visual: { color: "#C4956A", roughness: 0.6, metalness: 0, pattern: "wood-plank", patternScale: 1 },
    cost: { materialPerUnit: 350, laborPerUnit: 200, totalPerUnit: 550, unit: "EA" },
    schedule: { installRate: 6, crewSize: 2, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Solid Core Wood Door 1-3/4\"", thickness: 1.75 }], rValue: 0, fireRating: "20-MIN", stc: 30 },
    specSection: "08 14 00",
    ifcMaterial: "Wood Door",
  },
  {
    slug: "aluminum-entrance",
    name: "Aluminum Entrance Door 3'-0\" × 7'-0\"",
    manufacturer: "Kawneer",
    category: "doors-frames",
    visual: { color: "#B0B0B0", roughness: 0.2, metalness: 0.7, pattern: "glass", patternScale: 1, opacity: 0.4 },
    cost: { materialPerUnit: 2200, laborPerUnit: 600, totalPerUnit: 2800, unit: "EA" },
    schedule: { installRate: 3, crewSize: 2, leadTimeDays: 35 },
    assembly: { layers: [{ name: "Aluminum Frame + Glass Panel", thickness: 2 }], rValue: 0, fireRating: "0-HR", stc: 28 },
    specSection: "08 41 13",
    ifcMaterial: "Aluminum Entrance Door",
  },
  {
    slug: "overhead-door-12x14",
    name: "Insulated Overhead Door 12' × 14'",
    manufacturer: "Overhead Door",
    category: "doors-frames",
    visual: { color: "#E0E0E0", roughness: 0.4, metalness: 0.5, pattern: "horizontal-lap", patternScale: 14 },
    cost: { materialPerUnit: 4500, laborPerUnit: 1200, totalPerUnit: 5700, unit: "EA" },
    schedule: { installRate: 1, crewSize: 3, leadTimeDays: 28 },
    assembly: { layers: [{ name: "Insulated Steel Panel Door", thickness: 2 }], rValue: 12, fireRating: "", stc: 25 },
    specSection: "08 36 13",
    ifcMaterial: "Overhead Door",
  },
  {
    slug: "door-hardware-commercial",
    name: "Commercial Door Hardware Set",
    manufacturer: "Various",
    category: "doors-frames",
    visual: { color: "#C0C0C0", roughness: 0.2, metalness: 0.9, pattern: "chrome", patternScale: 1 },
    cost: { materialPerUnit: 450, laborPerUnit: 150, totalPerUnit: 600, unit: "EA" },
    schedule: { installRate: 8, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Lockset + Closer + Hinges", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "08 71 00",
    ifcMaterial: "Door Hardware",
  },
];

// ── 08 — Glazing & Curtain Wall ───────────────────────────────────
const GLAZING = [
  {
    slug: "curtain-wall-glass",
    name: "Curtain Wall — Insulated Glass",
    manufacturer: "Kawneer",
    category: "glazing",
    visual: { color: "#88C0D0", roughness: 0.1, metalness: 0.3, pattern: "glass", patternScale: 1, opacity: 0.4 },
    cost: { materialPerUnit: 35.00, laborPerUnit: 15.00, totalPerUnit: 50.00, unit: "SF" },
    schedule: { installRate: 50, crewSize: 4, leadTimeDays: 42 },
    assembly: { layers: [{ name: "1\" Insulated Glass Unit", thickness: 1 }, { name: "Aluminum Frame", thickness: 2 }], rValue: 3, fireRating: "0-HR", stc: 32 },
    specSection: "08 44 13",
    ifcMaterial: "Curtain Wall Glass",
  },
  {
    slug: "storefront-glass",
    name: "Aluminum Storefront",
    manufacturer: "Kawneer",
    category: "glazing",
    visual: { color: "#A8D0E0", roughness: 0.1, metalness: 0.2, pattern: "glass", patternScale: 1, opacity: 0.5 },
    cost: { materialPerUnit: 25.00, laborPerUnit: 10.00, totalPerUnit: 35.00, unit: "SF" },
    schedule: { installRate: 80, crewSize: 3, leadTimeDays: 28 },
    assembly: { layers: [{ name: "1\" Insulated Glass Unit", thickness: 1 }, { name: "Aluminum Storefront Frame", thickness: 1.75 }], rValue: 2, fireRating: "0-HR", stc: 30 },
    specSection: "08 41 13",
    ifcMaterial: "Aluminum Storefront",
  },
  {
    slug: "window-aluminum-fixed",
    name: "Aluminum Fixed Window 4' × 5'",
    manufacturer: "Various",
    category: "glazing",
    visual: { color: "#90C0D8", roughness: 0.1, metalness: 0.3, pattern: "glass", patternScale: 1, opacity: 0.45 },
    cost: { materialPerUnit: 650, laborPerUnit: 250, totalPerUnit: 900, unit: "EA" },
    schedule: { installRate: 8, crewSize: 2, leadTimeDays: 28 },
    assembly: { layers: [{ name: "1\" IGU", thickness: 1 }, { name: "Aluminum Frame", thickness: 3 }], rValue: 2, fireRating: "0-HR", stc: 30 },
    specSection: "08 51 13",
    ifcMaterial: "Aluminum Window",
  },
  {
    slug: "window-aluminum-operable",
    name: "Aluminum Operable Window 3' × 4'",
    manufacturer: "Various",
    category: "glazing",
    visual: { color: "#90C0D8", roughness: 0.1, metalness: 0.3, pattern: "glass", patternScale: 1, opacity: 0.45 },
    cost: { materialPerUnit: 800, laborPerUnit: 280, totalPerUnit: 1080, unit: "EA" },
    schedule: { installRate: 6, crewSize: 2, leadTimeDays: 28 },
    assembly: { layers: [{ name: "1\" IGU", thickness: 1 }, { name: "Aluminum Frame (operable)", thickness: 3 }], rValue: 2, fireRating: "0-HR", stc: 28 },
    specSection: "08 51 13",
    ifcMaterial: "Aluminum Window",
  },
  {
    slug: "skylight-unit",
    name: "Unit Skylight 4' × 4' Insulated",
    manufacturer: "Velux",
    category: "glazing",
    visual: { color: "#A0D0E8", roughness: 0.1, metalness: 0.2, pattern: "glass", patternScale: 1, opacity: 0.3 },
    cost: { materialPerUnit: 1800, laborPerUnit: 600, totalPerUnit: 2400, unit: "EA" },
    schedule: { installRate: 3, crewSize: 3, leadTimeDays: 35 },
    assembly: { layers: [{ name: "Insulated Glass Skylight", thickness: 1 }], rValue: 2, fireRating: "", stc: 25 },
    specSection: "08 63 00",
    ifcMaterial: "Skylight",
  },
];

// ── 09 — Interior Wall Finish ─────────────────────────────────────
const INTERIOR_WALL = [
  {
    slug: "gwb-1-layer",
    name: "5/8\" GWB on Metal Studs (1 Layer)",
    manufacturer: "USG",
    category: "interior-wall",
    visual: { color: "#F0EDE8", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.80, laborPerUnit: 4.50, totalPerUnit: 7.30, unit: "SF" },
    schedule: { installRate: 350, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "5/8\" GWB", thickness: 0.625 }, { name: "3-5/8\" Metal Stud 20ga", thickness: 3.625 }, { name: "5/8\" GWB", thickness: 0.625 }], rValue: 4, fireRating: "1-HR", stc: 40 },
    specSection: "09 21 16",
    ifcMaterial: "Gypsum Board on Metal Studs",
  },
  {
    slug: "gwb-2-layer",
    name: "5/8\" GWB on Metal Studs (2 Layer)",
    manufacturer: "USG",
    category: "interior-wall",
    visual: { color: "#F0EDE8", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 4.20, laborPerUnit: 6.00, totalPerUnit: 10.20, unit: "SF" },
    schedule: { installRate: 250, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "5/8\" GWB (x2)", thickness: 1.25 }, { name: "3-5/8\" Metal Stud 20ga", thickness: 3.625 }, { name: "5/8\" GWB (x2)", thickness: 1.25 }], rValue: 5, fireRating: "2-HR", stc: 50 },
    specSection: "09 21 16",
    ifcMaterial: "Gypsum Board on Metal Studs (2 Layer)",
  },
  {
    slug: "gwb-moisture-resistant",
    name: "5/8\" Moisture-Resistant GWB (Greenboard)",
    manufacturer: "USG",
    category: "interior-wall",
    visual: { color: "#D8E8D0", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.20, laborPerUnit: 4.50, totalPerUnit: 7.70, unit: "SF" },
    schedule: { installRate: 340, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "5/8\" MR GWB", thickness: 0.625 }, { name: "3-5/8\" Metal Stud", thickness: 3.625 }, { name: "5/8\" MR GWB", thickness: 0.625 }], rValue: 4, fireRating: "1-HR", stc: 40 },
    specSection: "09 29 00",
    ifcMaterial: "Moisture Resistant Gypsum Board",
  },
  {
    slug: "cement-board",
    name: "1/2\" Cement Board (Durock)",
    manufacturer: "USG",
    category: "interior-wall",
    visual: { color: "#C0C0B0", roughness: 0.8, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.50, laborPerUnit: 3.50, totalPerUnit: 6.00, unit: "SF" },
    schedule: { installRate: 300, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "1/2\" Cement Board", thickness: 0.5 }], rValue: 0, fireRating: "1-HR", stc: 0 },
    specSection: "09 29 00",
    ifcMaterial: "Cement Board",
  },
  {
    slug: "frp-wall-panel",
    name: "FRP Wall Panel (Fiberglass Reinforced)",
    manufacturer: "Crane Composites",
    category: "interior-wall",
    visual: { color: "#F0F0F0", roughness: 0.3, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 3.00, totalPerUnit: 6.50, unit: "SF" },
    schedule: { installRate: 300, crewSize: 2, leadTimeDays: 10 },
    assembly: { layers: [{ name: "FRP Panel 0.09\"", thickness: 0.09 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "09 77 00",
    ifcMaterial: "FRP Wall Panel",
  },
  {
    slug: "ceramic-wall-tile",
    name: "Ceramic Wall Tile 4\" × 4\"",
    manufacturer: "Daltile",
    category: "interior-wall",
    visual: { color: "#F0F0E8", roughness: 0.3, metalness: 0, pattern: "tile-grid", patternScale: 0.33 },
    cost: { materialPerUnit: 5.00, laborPerUnit: 8.00, totalPerUnit: 13.00, unit: "SF" },
    schedule: { installRate: 80, crewSize: 2, leadTimeDays: 10 },
    assembly: { layers: [{ name: "Ceramic Tile 1/4\"", thickness: 0.25 }, { name: "Thinset Mortar", thickness: 0.125 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "09 30 13",
    ifcMaterial: "Ceramic Wall Tile",
  },
];

// ── 09 — Flooring ─────────────────────────────────────────────────
const FLOORING = [
  {
    slug: "lvt-plank",
    name: "Luxury Vinyl Tile Plank",
    manufacturer: "Shaw",
    category: "flooring",
    visual: { color: "#B8A088", roughness: 0.4, metalness: 0, pattern: "wood-plank", patternScale: 6 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 3.00, totalPerUnit: 6.50, unit: "SF" },
    schedule: { installRate: 400, crewSize: 2, leadTimeDays: 10 },
    assembly: { layers: [{ name: "LVT Plank 5mm", thickness: 0.2 }, { name: "Underlayment", thickness: 0.08 }], rValue: 0, fireRating: "Class I", stc: 0 },
    specSection: "09 65 16",
    ifcMaterial: "Luxury Vinyl Tile",
  },
  {
    slug: "carpet-tile",
    name: "Carpet Tile 24\" × 24\"",
    manufacturer: "Interface",
    category: "flooring",
    visual: { color: "#7A7A7A", roughness: 0.9, metalness: 0, pattern: "carpet", patternScale: 2 },
    cost: { materialPerUnit: 2.75, laborPerUnit: 1.50, totalPerUnit: 4.25, unit: "SF" },
    schedule: { installRate: 600, crewSize: 2, leadTimeDays: 7 },
    assembly: { layers: [{ name: "Carpet Tile", thickness: 0.25 }], rValue: 1, fireRating: "Class I", stc: 0 },
    specSection: "09 68 13",
    ifcMaterial: "Carpet Tile",
  },
  {
    slug: "broadloom-carpet",
    name: "Broadloom Carpet (Commercial Grade)",
    manufacturer: "Shaw",
    category: "flooring",
    visual: { color: "#8A7A6A", roughness: 0.9, metalness: 0, pattern: "carpet", patternScale: 1 },
    cost: { materialPerUnit: 2.25, laborPerUnit: 1.75, totalPerUnit: 4.00, unit: "SF" },
    schedule: { installRate: 700, crewSize: 2, leadTimeDays: 7 },
    assembly: { layers: [{ name: "Broadloom Carpet", thickness: 0.375 }, { name: "Carpet Pad", thickness: 0.25 }], rValue: 2, fireRating: "Class I", stc: 0 },
    specSection: "09 68 00",
    ifcMaterial: "Broadloom Carpet",
  },
  {
    slug: "ceramic-tile",
    name: "Ceramic Floor Tile 12\" × 12\"",
    manufacturer: "Daltile",
    category: "flooring",
    visual: { color: "#D4C8B8", roughness: 0.4, metalness: 0, pattern: "tile-grid", patternScale: 1 },
    cost: { materialPerUnit: 4.50, laborPerUnit: 7.50, totalPerUnit: 12.00, unit: "SF" },
    schedule: { installRate: 100, crewSize: 2, leadTimeDays: 10 },
    assembly: { layers: [{ name: "Ceramic Tile 3/8\"", thickness: 0.375 }, { name: "Thinset Mortar", thickness: 0.125 }, { name: "Cement Board 1/4\"", thickness: 0.25 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "09 30 13",
    ifcMaterial: "Ceramic Tile",
  },
  {
    slug: "porcelain-tile",
    name: "Porcelain Floor Tile 24\" × 24\"",
    manufacturer: "Daltile",
    category: "flooring",
    visual: { color: "#E0D8C8", roughness: 0.3, metalness: 0.05, pattern: "tile-grid", patternScale: 2 },
    cost: { materialPerUnit: 7.00, laborPerUnit: 9.00, totalPerUnit: 16.00, unit: "SF" },
    schedule: { installRate: 80, crewSize: 2, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Porcelain Tile 3/8\"", thickness: 0.375 }, { name: "Thinset Mortar", thickness: 0.125 }, { name: "Cement Board 1/4\"", thickness: 0.25 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "09 30 13",
    ifcMaterial: "Porcelain Tile",
  },
  {
    slug: "vct-tile",
    name: "VCT (Vinyl Composition Tile) 12\" × 12\"",
    manufacturer: "Armstrong",
    category: "flooring",
    visual: { color: "#C8C0B0", roughness: 0.4, metalness: 0, pattern: "tile-grid", patternScale: 1 },
    cost: { materialPerUnit: 1.50, laborPerUnit: 2.00, totalPerUnit: 3.50, unit: "SF" },
    schedule: { installRate: 500, crewSize: 2, leadTimeDays: 5 },
    assembly: { layers: [{ name: "VCT Tile 1/8\"", thickness: 0.125 }], rValue: 0, fireRating: "Class I", stc: 0 },
    specSection: "09 65 13",
    ifcMaterial: "VCT Floor Tile",
  },
  {
    slug: "epoxy-floor",
    name: "Epoxy Floor Coating (2-coat)",
    manufacturer: "Various",
    category: "flooring",
    visual: { color: "#C0C0C0", roughness: 0.2, metalness: 0.1, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.00, laborPerUnit: 3.50, totalPerUnit: 6.50, unit: "SF" },
    schedule: { installRate: 400, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "Epoxy Topcoat", thickness: 0.02 }, { name: "Epoxy Primer", thickness: 0.01 }], rValue: 0, fireRating: "Class A", stc: 0 },
    specSection: "09 67 00",
    ifcMaterial: "Epoxy Floor Coating",
  },
  {
    slug: "rubber-flooring",
    name: "Rubber Flooring 3/8\"",
    manufacturer: "Mondo",
    category: "flooring",
    visual: { color: "#404040", roughness: 0.7, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 5.00, laborPerUnit: 3.00, totalPerUnit: 8.00, unit: "SF" },
    schedule: { installRate: 350, crewSize: 2, leadTimeDays: 10 },
    assembly: { layers: [{ name: "3/8\" Rubber Flooring", thickness: 0.375 }], rValue: 0, fireRating: "Class I", stc: 0 },
    specSection: "09 65 66",
    ifcMaterial: "Rubber Flooring",
  },
];

// ── 09 — Ceiling ──────────────────────────────────────────────────
const CEILING = [
  {
    slug: "act-2x4",
    name: "Acoustical Ceiling Tile 2' × 4'",
    manufacturer: "Armstrong",
    category: "ceiling",
    visual: { color: "#F5F5F0", roughness: 0.9, metalness: 0, pattern: "tile-grid", patternScale: 4 },
    cost: { materialPerUnit: 2.25, laborPerUnit: 2.75, totalPerUnit: 5.00, unit: "SF" },
    schedule: { installRate: 500, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "ACT Panel 5/8\"", thickness: 0.625 }, { name: "T-Bar Grid", thickness: 1.5 }], rValue: 1, fireRating: "Class A", stc: 35 },
    specSection: "09 51 13",
    ifcMaterial: "Acoustical Ceiling Tile",
  },
  {
    slug: "act-2x2",
    name: "Acoustical Ceiling Tile 2' × 2'",
    manufacturer: "Armstrong",
    category: "ceiling",
    visual: { color: "#F5F5F0", roughness: 0.9, metalness: 0, pattern: "tile-grid", patternScale: 2 },
    cost: { materialPerUnit: 2.50, laborPerUnit: 3.00, totalPerUnit: 5.50, unit: "SF" },
    schedule: { installRate: 450, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "ACT Panel 5/8\"", thickness: 0.625 }, { name: "T-Bar Grid", thickness: 1.5 }], rValue: 1, fireRating: "Class A", stc: 35 },
    specSection: "09 51 13",
    ifcMaterial: "Acoustical Ceiling Tile",
  },
  {
    slug: "gwb-ceiling",
    name: "5/8\" GWB Ceiling — Painted",
    manufacturer: "USG",
    category: "ceiling",
    visual: { color: "#FAFAF8", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.00, laborPerUnit: 5.50, totalPerUnit: 8.50, unit: "SF" },
    schedule: { installRate: 250, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "5/8\" GWB", thickness: 0.625 }], rValue: 0, fireRating: "1-HR", stc: 30 },
    specSection: "09 21 16",
    ifcMaterial: "Gypsum Board Ceiling",
  },
  {
    slug: "metal-panel-ceiling",
    name: "Metal Panel Ceiling (Linear)",
    manufacturer: "Armstrong",
    category: "ceiling",
    visual: { color: "#E0E0E0", roughness: 0.2, metalness: 0.6, pattern: "vertical-rib", patternScale: 1 },
    cost: { materialPerUnit: 6.00, laborPerUnit: 5.00, totalPerUnit: 11.00, unit: "SF" },
    schedule: { installRate: 200, crewSize: 3, leadTimeDays: 21 },
    assembly: { layers: [{ name: "Metal Ceiling Panel", thickness: 0.5 }], rValue: 0, fireRating: "Class A", stc: 25 },
    specSection: "09 51 33",
    ifcMaterial: "Metal Ceiling Panel",
  },
];

// ── 09 — Painting & Coatings ──────────────────────────────────────
const PAINTING = [
  {
    slug: "paint-interior-2coat",
    name: "Interior Latex Paint (2 Coats + Primer)",
    manufacturer: "Sherwin-Williams",
    category: "painting",
    visual: { color: "#F5F5F0", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 0.40, laborPerUnit: 1.10, totalPerUnit: 1.50, unit: "SF" },
    schedule: { installRate: 600, crewSize: 3, leadTimeDays: 3 },
    assembly: { layers: [{ name: "2 Coats Latex + Primer", thickness: 0.003 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "09 91 13",
    ifcMaterial: "Interior Paint",
  },
  {
    slug: "paint-exterior-2coat",
    name: "Exterior Latex Paint (2 Coats + Primer)",
    manufacturer: "Sherwin-Williams",
    category: "painting",
    visual: { color: "#F0F0E8", roughness: 0.8, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 0.50, laborPerUnit: 1.30, totalPerUnit: 1.80, unit: "SF" },
    schedule: { installRate: 500, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "2 Coats Exterior Latex + Primer", thickness: 0.004 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "09 91 13",
    ifcMaterial: "Exterior Paint",
  },
  {
    slug: "intumescent-fireproofing",
    name: "Intumescent Fireproofing (Steel)",
    manufacturer: "Various",
    category: "painting",
    visual: { color: "#E0E0E0", roughness: 0.6, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 5.00, laborPerUnit: 7.00, totalPerUnit: 12.00, unit: "SF" },
    schedule: { installRate: 200, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "Intumescent Coating", thickness: 0.04 }], rValue: 0, fireRating: "2-HR", stc: 0 },
    specSection: "07 81 00",
    ifcMaterial: "Intumescent Fireproofing",
  },
  {
    slug: "spray-fireproofing",
    name: "Spray-Applied Fireproofing (Cementitious)",
    manufacturer: "Carboline",
    category: "painting",
    visual: { color: "#D0D0D0", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.50, laborPerUnit: 3.00, totalPerUnit: 5.50, unit: "SF" },
    schedule: { installRate: 400, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "Cementitious Fireproofing 1\"", thickness: 1 }], rValue: 1, fireRating: "2-HR", stc: 0 },
    specSection: "07 81 00",
    ifcMaterial: "Spray-Applied Fireproofing",
  },
];

// ── 10 — Specialties ──────────────────────────────────────────────
const SPECIALTIES = [
  {
    slug: "toilet-partition",
    name: "Toilet Partition (Solid Plastic)",
    manufacturer: "Bobrick",
    category: "specialties",
    visual: { color: "#A0A0A0", roughness: 0.4, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1200, laborPerUnit: 400, totalPerUnit: 1600, unit: "EA" },
    schedule: { installRate: 4, crewSize: 2, leadTimeDays: 21 },
    assembly: { layers: [{ name: "HDPE Partition Panel", thickness: 1 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "10 21 13",
    ifcMaterial: "Toilet Partition",
  },
  {
    slug: "toilet-accessories",
    name: "Toilet Room Accessories Set",
    manufacturer: "Bobrick",
    category: "specialties",
    visual: { color: "#C0C0C0", roughness: 0.2, metalness: 0.8, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 350, laborPerUnit: 150, totalPerUnit: 500, unit: "EA" },
    schedule: { installRate: 8, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Paper holder + grab bars + hooks + mirror", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "10 28 00",
    ifcMaterial: "Toilet Accessories",
  },
  {
    slug: "fire-extinguisher-cabinet",
    name: "Fire Extinguisher Cabinet (Recessed)",
    manufacturer: "JL Industries",
    category: "specialties",
    visual: { color: "#CC0000", roughness: 0.3, metalness: 0.6, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 250, laborPerUnit: 100, totalPerUnit: 350, unit: "EA" },
    schedule: { installRate: 8, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Steel Cabinet + Extinguisher", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "10 44 00",
    ifcMaterial: "Fire Extinguisher Cabinet",
  },
  {
    slug: "lockers-single",
    name: "Single-Tier Locker 12\" × 18\" × 72\"",
    manufacturer: "Various",
    category: "specialties",
    visual: { color: "#4060A0", roughness: 0.3, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 350, laborPerUnit: 80, totalPerUnit: 430, unit: "EA" },
    schedule: { installRate: 12, crewSize: 2, leadTimeDays: 21 },
    assembly: { layers: [{ name: "Steel Locker", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "10 51 13",
    ifcMaterial: "Metal Locker",
  },
  {
    slug: "signage-interior",
    name: "Interior ADA Signage (per sign)",
    manufacturer: "Various",
    category: "specialties",
    visual: { color: "#1A1A6E", roughness: 0.3, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 75, laborPerUnit: 35, totalPerUnit: 110, unit: "EA" },
    schedule: { installRate: 20, crewSize: 1, leadTimeDays: 21 },
    assembly: { layers: [{ name: "ADA Tactile Sign", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "10 14 00",
    ifcMaterial: "Interior Signage",
  },
];

// ── 22 — Plumbing Fixtures ────────────────────────────────────────
const PLUMBING_FIXTURE = [
  {
    slug: "commercial-toilet",
    name: "Commercial Floor-Mount Toilet",
    manufacturer: "Kohler",
    category: "plumbing-fixture",
    visual: { color: "#FFFFFF", roughness: 0.2, metalness: 0.1, pattern: "porcelain", patternScale: 1 },
    cost: { materialPerUnit: 650, laborPerUnit: 350, totalPerUnit: 1000, unit: "EA" },
    schedule: { installRate: 3, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Toilet + Flush Valve", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 42 13",
    ifcMaterial: "Plumbing Fixture - Water Closet",
  },
  {
    slug: "commercial-toilet-wall",
    name: "Commercial Wall-Hung Toilet",
    manufacturer: "Kohler",
    category: "plumbing-fixture",
    visual: { color: "#FFFFFF", roughness: 0.2, metalness: 0.1, pattern: "porcelain", patternScale: 1 },
    cost: { materialPerUnit: 900, laborPerUnit: 450, totalPerUnit: 1350, unit: "EA" },
    schedule: { installRate: 2, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Wall-Hung Toilet + Carrier + Flush Valve", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 42 13",
    ifcMaterial: "Plumbing Fixture - Water Closet",
  },
  {
    slug: "commercial-urinal",
    name: "Wall-Mount Urinal w/ Flush Valve",
    manufacturer: "Kohler",
    category: "plumbing-fixture",
    visual: { color: "#FFFFFF", roughness: 0.2, metalness: 0.1, pattern: "porcelain", patternScale: 1 },
    cost: { materialPerUnit: 550, laborPerUnit: 300, totalPerUnit: 850, unit: "EA" },
    schedule: { installRate: 3, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Urinal + Flush Valve", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 42 16",
    ifcMaterial: "Plumbing Fixture - Urinal",
  },
  {
    slug: "commercial-lavatory",
    name: "Wall-Mount Lavatory w/ Faucet",
    manufacturer: "Kohler",
    category: "plumbing-fixture",
    visual: { color: "#FFFFFF", roughness: 0.2, metalness: 0.1, pattern: "porcelain", patternScale: 1 },
    cost: { materialPerUnit: 450, laborPerUnit: 280, totalPerUnit: 730, unit: "EA" },
    schedule: { installRate: 3, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Lavatory + Faucet + Trap", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 41 13",
    ifcMaterial: "Plumbing Fixture - Lavatory",
  },
  {
    slug: "counter-lavatory",
    name: "Countertop Lavatory (Drop-In) w/ Faucet",
    manufacturer: "Kohler",
    category: "plumbing-fixture",
    visual: { color: "#FFFFFF", roughness: 0.2, metalness: 0.1, pattern: "porcelain", patternScale: 1 },
    cost: { materialPerUnit: 350, laborPerUnit: 250, totalPerUnit: 600, unit: "EA" },
    schedule: { installRate: 4, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Drop-in Lav + Faucet + Trap", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 41 13",
    ifcMaterial: "Plumbing Fixture - Lavatory",
  },
  {
    slug: "mop-sink",
    name: "Floor-Mount Mop Sink 24\" × 24\"",
    manufacturer: "Zurn",
    category: "plumbing-fixture",
    visual: { color: "#D0D0D0", roughness: 0.5, metalness: 0.2, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 400, laborPerUnit: 300, totalPerUnit: 700, unit: "EA" },
    schedule: { installRate: 2, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Terrazzo Mop Sink + Faucet", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 41 00",
    ifcMaterial: "Plumbing Fixture - Service Sink",
  },
  {
    slug: "drinking-fountain",
    name: "Wall-Mount Drinking Fountain (ADA)",
    manufacturer: "Elkay",
    category: "plumbing-fixture",
    visual: { color: "#C0C0C0", roughness: 0.2, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 800, laborPerUnit: 350, totalPerUnit: 1150, unit: "EA" },
    schedule: { installRate: 2, crewSize: 1, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Drinking Fountain + Bottle Filler", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 47 00",
    ifcMaterial: "Plumbing Fixture - Drinking Fountain",
  },
  {
    slug: "water-heater-commercial",
    name: "Commercial Gas Water Heater 100 gal",
    manufacturer: "A.O. Smith",
    category: "plumbing-fixture",
    visual: { color: "#E8E8E8", roughness: 0.5, metalness: 0.3, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 4500, laborPerUnit: 1500, totalPerUnit: 6000, unit: "EA" },
    schedule: { installRate: 1, crewSize: 2, leadTimeDays: 21 },
    assembly: { layers: [{ name: "100 gal Gas Water Heater", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "22 34 00",
    ifcMaterial: "Water Heater",
  },
];

// ── 21 — Fire Suppression ─────────────────────────────────────────
const FIRE_SUPPRESSION = [
  {
    slug: "sprinkler-wet-light",
    name: "Wet Pipe Sprinkler — Light Hazard",
    manufacturer: "Viking",
    category: "fire-suppression",
    visual: { color: "#CC0000", roughness: 0.3, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.50, laborPerUnit: 3.50, totalPerUnit: 6.00, unit: "SF" },
    schedule: { installRate: 300, crewSize: 4, leadTimeDays: 21 },
    assembly: { layers: [{ name: "1\" Black Steel Pipe + Heads", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "21 13 13",
    ifcMaterial: "Fire Sprinkler System",
  },
  {
    slug: "sprinkler-wet-ordinary",
    name: "Wet Pipe Sprinkler — Ordinary Hazard",
    manufacturer: "Viking",
    category: "fire-suppression",
    visual: { color: "#CC0000", roughness: 0.3, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 4.50, totalPerUnit: 8.00, unit: "SF" },
    schedule: { installRate: 250, crewSize: 4, leadTimeDays: 28 },
    assembly: { layers: [{ name: "1.5\" Black Steel Pipe + Heads", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "21 13 13",
    ifcMaterial: "Fire Sprinkler System",
  },
  {
    slug: "fire-alarm-system",
    name: "Fire Alarm System (per device)",
    manufacturer: "Various",
    category: "fire-suppression",
    visual: { color: "#CC0000", roughness: 0.4, metalness: 0.3, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 250, laborPerUnit: 150, totalPerUnit: 400, unit: "EA" },
    schedule: { installRate: 8, crewSize: 2, leadTimeDays: 21 },
    assembly: { layers: [{ name: "Detection Device + Wiring", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "21 30 00",
    ifcMaterial: "Fire Alarm Device",
  },
];

// ── 23 — HVAC ─────────────────────────────────────────────────────
const HVAC = [
  {
    slug: "rtu-5ton",
    name: "Rooftop Unit 5-Ton",
    manufacturer: "Carrier",
    category: "hvac",
    visual: { color: "#B0B0B0", roughness: 0.4, metalness: 0.6, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 8000, laborPerUnit: 3000, totalPerUnit: 11000, unit: "EA" },
    schedule: { installRate: 1, crewSize: 4, leadTimeDays: 42 },
    assembly: { layers: [{ name: "5-Ton Packaged RTU", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "23 74 00",
    ifcMaterial: "Rooftop Unit",
  },
  {
    slug: "rtu-10ton",
    name: "Rooftop Unit 10-Ton",
    manufacturer: "Carrier",
    category: "hvac",
    visual: { color: "#B0B0B0", roughness: 0.4, metalness: 0.6, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 14000, laborPerUnit: 5000, totalPerUnit: 19000, unit: "EA" },
    schedule: { installRate: 1, crewSize: 4, leadTimeDays: 56 },
    assembly: { layers: [{ name: "10-Ton Packaged RTU", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "23 74 00",
    ifcMaterial: "Rooftop Unit",
  },
  {
    slug: "vav-box",
    name: "VAV Box w/ Reheat Coil",
    manufacturer: "Trane",
    category: "hvac",
    visual: { color: "#A0A0A0", roughness: 0.4, metalness: 0.5, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1800, laborPerUnit: 800, totalPerUnit: 2600, unit: "EA" },
    schedule: { installRate: 3, crewSize: 2, leadTimeDays: 28 },
    assembly: { layers: [{ name: "VAV Box + Hot Water Reheat", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "23 36 00",
    ifcMaterial: "VAV Terminal Unit",
  },
  {
    slug: "ductwork-rectangular",
    name: "Galv. Rectangular Ductwork (per lb)",
    manufacturer: "Various",
    category: "hvac",
    visual: { color: "#C0C0C0", roughness: 0.3, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 5.50, totalPerUnit: 9.00, unit: "LB" },
    schedule: { installRate: 200, crewSize: 3, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Galv Sheet Metal Duct", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "23 31 13",
    ifcMaterial: "Sheet Metal Ductwork",
  },
  {
    slug: "duct-insulation",
    name: "Duct Insulation 1.5\" Fiberglass Wrap",
    manufacturer: "Knauf",
    category: "hvac",
    visual: { color: "#D0D0D0", roughness: 0.8, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 1.50, laborPerUnit: 2.00, totalPerUnit: 3.50, unit: "SF" },
    schedule: { installRate: 400, crewSize: 2, leadTimeDays: 7 },
    assembly: { layers: [{ name: "1.5\" Fiberglass Wrap + FSK", thickness: 1.5 }], rValue: 6, fireRating: "", stc: 0 },
    specSection: "23 07 00",
    ifcMaterial: "Duct Insulation",
  },
  {
    slug: "diffuser-supply",
    name: "Supply Air Diffuser 24\" × 24\"",
    manufacturer: "Titus",
    category: "hvac",
    visual: { color: "#F0F0F0", roughness: 0.3, metalness: 0.5, pattern: "tile-grid", patternScale: 2 },
    cost: { materialPerUnit: 120, laborPerUnit: 80, totalPerUnit: 200, unit: "EA" },
    schedule: { installRate: 12, crewSize: 2, leadTimeDays: 14 },
    assembly: { layers: [{ name: "24\"×24\" Ceiling Diffuser", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "23 33 00",
    ifcMaterial: "Supply Air Diffuser",
  },
  {
    slug: "mini-split-system",
    name: "Ductless Mini-Split 1.5-Ton",
    manufacturer: "Mitsubishi",
    category: "hvac",
    visual: { color: "#F0F0F0", roughness: 0.3, metalness: 0.3, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3000, laborPerUnit: 1500, totalPerUnit: 4500, unit: "EA" },
    schedule: { installRate: 1, crewSize: 2, leadTimeDays: 14 },
    assembly: { layers: [{ name: "Indoor + Outdoor Unit + Lineset", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "23 81 00",
    ifcMaterial: "Ductless Split System",
  },
];

// ── 26 — Electrical ───────────────────────────────────────────────
const ELECTRICAL = [
  {
    slug: "2x4-led-troffer",
    name: "2' × 4' LED Troffer 40W",
    manufacturer: "Lithonia",
    category: "electrical",
    visual: { color: "#F5F5F5", roughness: 0.3, metalness: 0.4, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 180, laborPerUnit: 120, totalPerUnit: 300, unit: "EA" },
    schedule: { installRate: 10, crewSize: 2, leadTimeDays: 14 },
    assembly: { layers: [{ name: "LED Troffer + Driver", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 51 13",
    ifcMaterial: "LED Troffer",
  },
  {
    slug: "led-downlight-6",
    name: "6\" LED Downlight Recessed",
    manufacturer: "Various",
    category: "electrical",
    visual: { color: "#F0F0F0", roughness: 0.3, metalness: 0.3, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 85, laborPerUnit: 75, totalPerUnit: 160, unit: "EA" },
    schedule: { installRate: 12, crewSize: 2, leadTimeDays: 14 },
    assembly: { layers: [{ name: "6\" Recessed LED Can", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 51 13",
    ifcMaterial: "LED Downlight",
  },
  {
    slug: "led-exit-sign",
    name: "LED Exit Sign w/ Emergency Lights",
    manufacturer: "Lithonia",
    category: "electrical",
    visual: { color: "#CC0000", roughness: 0.3, metalness: 0.3, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 120, laborPerUnit: 100, totalPerUnit: 220, unit: "EA" },
    schedule: { installRate: 10, crewSize: 1, leadTimeDays: 10 },
    assembly: { layers: [{ name: "Exit/Emergency Combo", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 53 00",
    ifcMaterial: "Exit Sign",
  },
  {
    slug: "duplex-receptacle",
    name: "Duplex Receptacle 20A (installed)",
    manufacturer: "Leviton",
    category: "electrical",
    visual: { color: "#F0F0F0", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 25, laborPerUnit: 85, totalPerUnit: 110, unit: "EA" },
    schedule: { installRate: 10, crewSize: 1, leadTimeDays: 7 },
    assembly: { layers: [{ name: "Receptacle + Box + Wire", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 27 26",
    ifcMaterial: "Electrical Receptacle",
  },
  {
    slug: "light-switch",
    name: "Single Pole Light Switch (installed)",
    manufacturer: "Leviton",
    category: "electrical",
    visual: { color: "#F0F0F0", roughness: 0.5, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 15, laborPerUnit: 75, totalPerUnit: 90, unit: "EA" },
    schedule: { installRate: 12, crewSize: 1, leadTimeDays: 7 },
    assembly: { layers: [{ name: "Switch + Box + Wire", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 27 26",
    ifcMaterial: "Light Switch",
  },
  {
    slug: "panel-200a",
    name: "Electrical Panel 200A 42-Circuit",
    manufacturer: "Square D",
    category: "electrical",
    visual: { color: "#808080", roughness: 0.4, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2500, laborPerUnit: 1500, totalPerUnit: 4000, unit: "EA" },
    schedule: { installRate: 1, crewSize: 2, leadTimeDays: 21 },
    assembly: { layers: [{ name: "200A Main Breaker Panel", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 24 16",
    ifcMaterial: "Electrical Panel",
  },
  {
    slug: "conduit-emt-3-4",
    name: "EMT Conduit 3/4\" (installed)",
    manufacturer: "Various",
    category: "electrical",
    visual: { color: "#C0C0C0", roughness: 0.3, metalness: 0.8, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 3.50, laborPerUnit: 6.50, totalPerUnit: 10.00, unit: "LF" },
    schedule: { installRate: 100, crewSize: 1, leadTimeDays: 5 },
    assembly: { layers: [{ name: "3/4\" EMT + Fittings", thickness: 0.75 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 05 33",
    ifcMaterial: "EMT Conduit",
  },
  {
    slug: "transformer-75kva",
    name: "Dry-Type Transformer 75kVA",
    manufacturer: "Square D",
    category: "electrical",
    visual: { color: "#808080", roughness: 0.5, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 5500, laborPerUnit: 2000, totalPerUnit: 7500, unit: "EA" },
    schedule: { installRate: 1, crewSize: 2, leadTimeDays: 28 },
    assembly: { layers: [{ name: "75kVA Dry-Type Transformer", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "26 22 00",
    ifcMaterial: "Transformer",
  },
];

// ── 31/32 — Sitework & Earthwork ──────────────────────────────────
const SITEWORK = [
  {
    slug: "excavation-bulk",
    name: "Bulk Excavation (Machine)",
    manufacturer: "N/A",
    category: "sitework",
    visual: { color: "#8B6E4E", roughness: 0.95, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 0, laborPerUnit: 4.50, totalPerUnit: 4.50, unit: "CY" },
    schedule: { installRate: 200, crewSize: 3, leadTimeDays: 3 },
    assembly: { layers: [{ name: "Bulk Earth Excavation", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "31 23 16",
    ifcMaterial: "Earthwork",
  },
  {
    slug: "gravel-base-4",
    name: "Gravel Base 4\" (Compacted)",
    manufacturer: "N/A",
    category: "sitework",
    visual: { color: "#A09080", roughness: 0.9, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 0.80, laborPerUnit: 0.70, totalPerUnit: 1.50, unit: "SF" },
    schedule: { installRate: 1000, crewSize: 3, leadTimeDays: 2 },
    assembly: { layers: [{ name: "4\" Compacted Gravel", thickness: 4 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "31 05 00",
    ifcMaterial: "Gravel Base",
  },
  {
    slug: "asphalt-paving",
    name: "Asphalt Paving 3\" (Parking Lot)",
    manufacturer: "N/A",
    category: "sitework",
    visual: { color: "#404040", roughness: 0.7, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 2.50, laborPerUnit: 2.00, totalPerUnit: 4.50, unit: "SF" },
    schedule: { installRate: 2000, crewSize: 6, leadTimeDays: 5 },
    assembly: { layers: [{ name: "3\" Asphalt", thickness: 3 }, { name: "6\" Gravel Base", thickness: 6 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "32 12 16",
    ifcMaterial: "Asphalt Paving",
  },
  {
    slug: "concrete-sidewalk",
    name: "Concrete Sidewalk 4\"",
    manufacturer: "N/A",
    category: "sitework",
    visual: { color: "#C8C8C8", roughness: 0.6, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 5.00, laborPerUnit: 4.50, totalPerUnit: 9.50, unit: "SF" },
    schedule: { installRate: 300, crewSize: 4, leadTimeDays: 3 },
    assembly: { layers: [{ name: "4\" Concrete Sidewalk", thickness: 4 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "32 13 13",
    ifcMaterial: "Concrete Sidewalk",
  },
  {
    slug: "concrete-curb",
    name: "Concrete Curb & Gutter",
    manufacturer: "N/A",
    category: "sitework",
    visual: { color: "#C0C0C0", roughness: 0.7, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 18.00, laborPerUnit: 14.00, totalPerUnit: 32.00, unit: "LF" },
    schedule: { installRate: 100, crewSize: 4, leadTimeDays: 3 },
    assembly: { layers: [{ name: "Concrete Curb 6\"×18\"", thickness: 6 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "32 16 13",
    ifcMaterial: "Concrete Curb",
  },
  {
    slug: "chain-link-fence-6",
    name: "Chain Link Fence 6' h w/ Top Rail",
    manufacturer: "Various",
    category: "sitework",
    visual: { color: "#A0A0A0", roughness: 0.4, metalness: 0.7, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 16.00, laborPerUnit: 10.00, totalPerUnit: 26.00, unit: "LF" },
    schedule: { installRate: 80, crewSize: 3, leadTimeDays: 7 },
    assembly: { layers: [{ name: "6' Chain Link + Posts", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "32 31 13",
    ifcMaterial: "Chain Link Fence",
  },
  {
    slug: "site-storm-pipe-8",
    name: "8\" PVC Storm Drain Pipe",
    manufacturer: "Various",
    category: "sitework",
    visual: { color: "#005500", roughness: 0.4, metalness: 0, pattern: "smooth", patternScale: 1 },
    cost: { materialPerUnit: 12.00, laborPerUnit: 14.00, totalPerUnit: 26.00, unit: "LF" },
    schedule: { installRate: 60, crewSize: 3, leadTimeDays: 5 },
    assembly: { layers: [{ name: "8\" PVC SDR 35 Pipe", thickness: 0 }], rValue: 0, fireRating: "", stc: 0 },
    specSection: "33 41 00",
    ifcMaterial: "Storm Drain Pipe",
  },
];

// ── Combined catalog ─────────────────────────────────────────────
export const MATERIAL_CATALOG = [
  ...CONCRETE,
  ...METALS,
  ...WOOD_FRAMING,
  ...EXTERIOR_CLADDING,
  ...ROOFING,
  ...WATERPROOFING,
  ...DOORS_FRAMES,
  ...GLAZING,
  ...INTERIOR_WALL,
  ...FLOORING,
  ...CEILING,
  ...PAINTING,
  ...SPECIALTIES,
  ...PLUMBING_FIXTURE,
  ...FIRE_SUPPRESSION,
  ...HVAC,
  ...ELECTRICAL,
  ...SITEWORK,
];

// Slug → material index for O(1) lookup
export const MATERIAL_INDEX = Object.fromEntries(MATERIAL_CATALOG.map(m => [m.slug, m]));
