import { describe, it, expect, beforeEach } from "vitest";
import { useDrawingPipelineStore } from "@/stores/drawingPipelineStore";

describe("modelStore", () => {
  beforeEach(() => {
    useDrawingPipelineStore.getState().reset();
  });

  // ── Initial state ──────────────────────────────────────────────
  it("has correct initial state", () => {
    const s = useDrawingPipelineStore.getState();
    expect(s.elements).toEqual([]);
    expect(s.selectedElementId).toBeNull();
    expect(s.viewMode).toBe("trade");
    expect(s.ifcLoaded).toBe(false);
    expect(s.autoGenerated).toBe(false);
    expect(s.generating).toBe(false);
    expect(s.outlines).toEqual({});
    expect(s.floorAssignments).toEqual({});
    expect(s.floorHeights).toEqual({});
    expect(s.specOverrides).toEqual({});
    expect(s.xrayMode).toBe(false);
    expect(s.hiddenFloors).toEqual([]);
    expect(s.sectionPlaneY).toBeNull();
  });

  // ── Actions ─────────────────────────────────────────────────────
  it("sets elements", () => {
    useDrawingPipelineStore.getState().setElements([{ id: "e1", type: "wall" }]);
    expect(useDrawingPipelineStore.getState().elements).toHaveLength(1);
    expect(useDrawingPipelineStore.getState().elements[0].id).toBe("e1");
  });

  it("sets view mode", () => {
    useDrawingPipelineStore.getState().setViewMode("cost");
    expect(useDrawingPipelineStore.getState().viewMode).toBe("cost");
  });

  it("sets outline for a drawing", () => {
    const poly = [{ x: 0, z: 0 }, { x: 10, z: 0 }, { x: 10, z: 8 }];
    useDrawingPipelineStore.getState().setOutline("d1", poly, "ai");
    expect(useDrawingPipelineStore.getState().outlines.d1.polygon).toEqual(poly);
    expect(useDrawingPipelineStore.getState().outlines.d1.source).toBe("ai");
  });

  it("sets floor height overrides", () => {
    useDrawingPipelineStore.getState().setFloorHeightFor("Level 1", 14);
    useDrawingPipelineStore.getState().setFloorHeightFor("Level 2", 12);
    expect(useDrawingPipelineStore.getState().floorHeights["Level 1"]).toBe(14);
    expect(useDrawingPipelineStore.getState().floorHeights["Level 2"]).toBe(12);
  });

  it("sets and clears spec overrides", () => {
    useDrawingPipelineStore.getState().setSpecOverride("e1", { material: "brick", costOverride: 12 });
    expect(useDrawingPipelineStore.getState().specOverrides.e1.material).toBe("brick");

    useDrawingPipelineStore.getState().setSpecOverride("e1", { finish: "painted" });
    expect(useDrawingPipelineStore.getState().specOverrides.e1.material).toBe("brick");
    expect(useDrawingPipelineStore.getState().specOverrides.e1.finish).toBe("painted");

    useDrawingPipelineStore.getState().clearSpecOverride("e1");
    expect(useDrawingPipelineStore.getState().specOverrides.e1).toBeUndefined();
  });

  it("toggles floor visibility", () => {
    useDrawingPipelineStore.getState().toggleFloorVisibility("Level 1");
    expect(useDrawingPipelineStore.getState().hiddenFloors).toContain("Level 1");

    useDrawingPipelineStore.getState().toggleFloorVisibility("Level 1");
    expect(useDrawingPipelineStore.getState().hiddenFloors).not.toContain("Level 1");
  });

  it("sets section plane Y", () => {
    useDrawingPipelineStore.getState().setSectionPlaneY(24);
    expect(useDrawingPipelineStore.getState().sectionPlaneY).toBe(24);
  });

  it("sets xray mode", () => {
    useDrawingPipelineStore.getState().setXrayMode(true);
    expect(useDrawingPipelineStore.getState().xrayMode).toBe(true);
  });

  it("getSelectedElement returns correct element", () => {
    useDrawingPipelineStore.getState().setElements([
      { id: "e1", type: "wall" },
      { id: "e2", type: "slab" },
    ]);
    useDrawingPipelineStore.getState().setSelectedElementId("e2");
    expect(useDrawingPipelineStore.getState().getSelectedElement().type).toBe("slab");
  });

  it("getSelectedElement returns null when nothing selected", () => {
    expect(useDrawingPipelineStore.getState().getSelectedElement()).toBeNull();
  });

  // ── Reset ──────────────────────────────────────────────────────
  it("reset clears all state", () => {
    useDrawingPipelineStore.getState().setElements([{ id: "e1" }]);
    useDrawingPipelineStore.getState().setViewMode("cost");
    useDrawingPipelineStore.getState().setOutline("d1", [{ x: 0, z: 0 }], "manual");
    useDrawingPipelineStore.getState().setFloorHeightFor("Level 1", 14);
    useDrawingPipelineStore.getState().setSpecOverride("e1", { material: "brick" });
    useDrawingPipelineStore.getState().setXrayMode(true);

    useDrawingPipelineStore.getState().reset();

    const s = useDrawingPipelineStore.getState();
    expect(s.elements).toEqual([]);
    expect(s.viewMode).toBe("trade");
    expect(s.outlines).toEqual({});
    expect(s.floorHeights).toEqual({});
    expect(s.specOverrides).toEqual({});
    expect(s.xrayMode).toBe(false);
  });

  // ── Persistence shape ──────────────────────────────────────────
  // These tests verify the shape of data we'll persist in the estimate blob
  describe("persistence data shape", () => {
    it("metadata fields are serializable (no functions, no circular refs)", () => {
      useDrawingPipelineStore.getState().setOutline("d1", [{ x: 0, z: 0 }, { x: 10, z: 5 }], "ai");
      useDrawingPipelineStore.getState().setFloorHeightFor("Level 1", 14);
      useDrawingPipelineStore.getState().setSpecOverride("e1", { material: "hardie-lap", costOverride: 10.75 });
      useDrawingPipelineStore.getState().setViewMode("cost");

      const s = useDrawingPipelineStore.getState();
      const persistable = {
        outlines: s.outlines,
        floorAssignments: s.floorAssignments,
        floorHeights: s.floorHeights,
        specOverrides: s.specOverrides,
        viewMode: s.viewMode,
        autoGenerated: s.autoGenerated,
        ifcLoaded: s.ifcLoaded,
        floorHeight: s.floorHeight,
      };

      // Should serialize and deserialize without loss
      const json = JSON.stringify(persistable);
      const parsed = JSON.parse(json);
      expect(parsed.outlines.d1.polygon).toEqual([{ x: 0, z: 0 }, { x: 10, z: 5 }]);
      expect(parsed.floorHeights["Level 1"]).toBe(14);
      expect(parsed.specOverrides.e1.material).toBe("hardie-lap");
      expect(parsed.viewMode).toBe("cost");
    });

    it("IFC elements with geometry arrays are serializable", () => {
      const ifcElement = {
        id: "ifc-42",
        type: "wall",
        geometry: {
          kind: "ifcMesh",
          vertices: [0, 0, 0, 1, 0, 0, 1, 1, 0],
          indices: [0, 1, 2],
          matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
        },
      };
      useDrawingPipelineStore.getState().setElements([ifcElement]);
      useDrawingPipelineStore.setState({ ifcLoaded: true });

      const s = useDrawingPipelineStore.getState();
      const json = JSON.stringify(s.elements);
      const parsed = JSON.parse(json);
      expect(parsed[0].geometry.vertices).toEqual([0, 0, 0, 1, 0, 0, 1, 1, 0]);
      expect(parsed[0].geometry.kind).toBe("ifcMesh");
    });
  });
});
