import { create } from 'zustand';

export const useModelStore = create((set, get) => ({
  // 3D elements: { id, type, geometry (serialized), trade, linkedItemId, cost, properties, level }
  elements: [],
  selectedElementId: null,
  viewMode: 'trade',        // 'trade' | 'cost' | 'gaps' | 'presentation' | 'coverage'
  levels: [],               // { id, name, elevation, sheetId }
  ifcLoaded: false,
  autoGenerated: false,
  generating: false,
  ifcElements: [],           // Raw IFC element data
  ifcError: null,

  // Plan outline + coverage state
  outlines: {},              // { [drawingId]: { polygon: [{x,z}], source: 'ai'|'manual' } }
  floorAssignments: {},      // { [drawingId]: { floor, elevation, label } }
  coverageCells: [],         // GridCell[] from coverageGrid
  coverageStats: null,       // { total, covered, gap, pct }
  floorHeight: 12,           // default feet per story (fallback)
  floorHeights: {},          // { [floorLabel]: number } per-floor height overrides
  analyzingPlans: false,     // loading state for AI outline detection
  analyzeProgress: '',       // progress text during analysis

  // Room geometry from geometryEngine analysis
  // { [drawingId]: { rooms: Room[], roomLabels: RoomLabel[] } }
  roomGeometry: {},
  roomElements: [],           // 3D room outline elements for rendering

  // Interactive 3D features
  hoveredElementId: null,    // element under cursor
  hiddenFloors: [],          // storey names to hide
  sectionPlaneY: null,       // null = disabled, number = Y clip height
  specOverrides: {},         // { [elementId]: { material, assembly, finish, notes, costOverride } }
  xrayMode: false,           // see-through mode

  // Material assignments
  materialAssignments: {},   // { [elementId]: { slug, overrides: {} } }

  // Actions
  setElements: (v) => set({ elements: v }),
  setSelectedElementId: (v) => set({ selectedElementId: v }),
  setViewMode: (v) => set({ viewMode: v }),
  setLevels: (v) => set({ levels: v }),
  setGenerating: (v) => set({ generating: v }),
  setIfcLoaded: (v) => set({ ifcLoaded: v }),
  setIfcElements: (v) => set({ ifcElements: v }),
  setIfcError: (v) => set({ ifcError: v }),

  selectElement: (id) => set({ selectedElementId: id }),

  // Plan outline + coverage actions
  setOutline: (drawingId, polygon, source = 'ai', pixelPolygon = null) => set(s => ({
    outlines: { ...s.outlines, [drawingId]: { polygon, source, pixelPolygon } },
  })),
  setFloorAssignments: (map) => set({ floorAssignments: map }),
  setCoverage: (cells, stats) => set({ coverageCells: cells, coverageStats: stats }),
  setFloorHeight: (ft) => set({ floorHeight: ft }),
  setFloorHeightFor: (label, ft) => set(s => ({
    floorHeights: { ...s.floorHeights, [label]: ft },
  })),
  setAnalyzingPlans: (v) => set({ analyzingPlans: v }),
  setAnalyzeProgress: (v) => set({ analyzeProgress: v }),
  setRoomGeometry: (drawingId, rooms, roomLabels) => set(s => ({
    roomGeometry: { ...s.roomGeometry, [drawingId]: { rooms, roomLabels } },
  })),
  setRoomElements: (v) => set({ roomElements: v }),

  // Interactive 3D actions
  setHoveredElement: (id) => set({ hoveredElementId: id }),
  toggleFloorVisibility: (floorName) => set(s => {
    const hidden = [...s.hiddenFloors];
    const idx = hidden.indexOf(floorName);
    if (idx >= 0) hidden.splice(idx, 1);
    else hidden.push(floorName);
    return { hiddenFloors: hidden };
  }),
  showAllFloors: () => set({ hiddenFloors: [] }),
  setSectionPlaneY: (y) => set({ sectionPlaneY: y }),
  setSpecOverride: (elementId, overrides) => set(s => ({
    specOverrides: {
      ...s.specOverrides,
      [elementId]: { ...(s.specOverrides[elementId] || {}), ...overrides },
    },
  })),
  clearSpecOverride: (elementId) => set(s => {
    const next = { ...s.specOverrides };
    delete next[elementId];
    return { specOverrides: next };
  }),
  setXrayMode: (v) => set({ xrayMode: v }),

  // Material assignment actions
  assignMaterial: (elementId, slug, overrides = {}) => set(s => ({
    materialAssignments: {
      ...s.materialAssignments,
      [elementId]: { slug, overrides },
    },
  })),
  removeMaterialAssignment: (elementId) => set(s => {
    const next = { ...s.materialAssignments };
    delete next[elementId];
    return { materialAssignments: next };
  }),
  updateMaterialOverrides: (elementId, overrides) => set(s => ({
    materialAssignments: {
      ...s.materialAssignments,
      [elementId]: {
        ...(s.materialAssignments[elementId] || {}),
        overrides: { ...(s.materialAssignments[elementId]?.overrides || {}), ...overrides },
      },
    },
  })),

  getSelectedElement: () => {
    const { elements, selectedElementId } = get();
    return elements.find(e => e.id === selectedElementId) || null;
  },

  reset: () => set({
    elements: [],
    selectedElementId: null,
    viewMode: 'trade',
    levels: [],
    ifcLoaded: false,
    autoGenerated: false,
    generating: false,
    ifcElements: [],
    ifcError: null,
    outlines: {},
    floorAssignments: {},
    coverageCells: [],
    coverageStats: null,
    floorHeight: 12,
    floorHeights: {},
    analyzingPlans: false,
    analyzeProgress: '',
    hoveredElementId: null,
    hiddenFloors: [],
    sectionPlaneY: null,
    specOverrides: {},
    xrayMode: false,
    materialAssignments: {},
    roomGeometry: {},
    roomElements: [],
  }),
}));
