// ═══════════════════════════════════════════════════════════════════════════════
// NOVA Autopilot — Fully automated estimate generation
//
// Input:  PDF file(s) + minimal metadata (building type, SF, location)
// Output: Complete estimate with ROM, scope items, line items, confidence scores
//
// This is NOT a new scan pipeline — it orchestrates the existing one with:
//   1. Auto-decisions (accept all high-confidence predictions)
//   2. Self-verification (uses scanVerifier via romEngine)
//   3. Quality scoring
//   4. Progress callbacks for UI
//
// Usage:
//   import { runAutopilot } from "@/utils/novaAutopilot";
//   const result = await runAutopilot({
//     pdfFiles: [file1, file2],
//     buildingType: "commercial-office",
//     projectSF: 25000,
//     location: "New York, NY",
//     projectName: "28 Liberty - 22nd Floor",
//     onProgress: (phase, pct, message) => {},
//     signal: abortController.signal,
//   });
//
// All state reads use getState() — works outside React render context.
// Heavy modules are dynamically imported to keep the main bundle lean.
// ═══════════════════════════════════════════════════════════════════════════════

import { useEstimatesStore } from "@/stores/estimatesStore";
import { useProjectStore } from "@/stores/projectStore";
import { useItemsStore } from "@/stores/itemsStore";
import { useDrawingsStore } from "@/stores/drawingsStore";
import { useScanStore } from "@/stores/scanStore";
import { useNovaStore } from "@/stores/novaStore";
import { useUiStore } from "@/stores/uiStore";
import { uid, today, nowStr } from "@/utils/format";
import { autoTradeFromCode } from "@/constants/tradeGroupings";
import { autoDirective } from "@/utils/directives";

// ─── Abort helper ────────────────────────────────────────────────────────────
function checkAbort(signal) {
  if (signal?.aborted) throw new AutopilotAbortError();
}

class AutopilotAbortError extends Error {
  constructor() {
    super("Autopilot aborted");
    this.name = "AutopilotAbortError";
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// runAutopilot — Full pipeline: PDF upload → scan → ROM → scope → estimate
// ═══════════════════════════════════════════════════════════════════════════════
export async function runAutopilot({
  pdfFiles = [],
  buildingType = "commercial-office",
  projectSF = 0,
  location = "",
  projectName = "Autopilot Estimate",
  clientName = "",
  workType = "new-construction",
  laborType = "open_shop",
  onProgress = () => {},
  signal,
} = {}) {
  const startTime = Date.now();

  onProgress("init", 0, "Initializing NOVA Autopilot...");
  checkAbort(signal);

  // ── Phase 1: Create estimate environment ──────────────────────────────────
  const estimateId = uid();
  const settings = useUiStore.getState().appSettings || {};
  const { ownerId, orgId } = useEstimatesStore.getState()._getOwnership?.() || {};

  // Add to estimates index (lightweight — no template resolution needed)
  const newEntry = {
    id: estimateId,
    name: projectName,
    estimateNumber: "",
    client: clientName,
    status: "Estimating",
    bidDue: "",
    startDate: today(),
    estimatedHours: 0,
    grandTotal: 0,
    elementCount: 0,
    lastModified: nowStr(),
    estimator: "",
    coEstimators: [],
    jobType: buildingType,
    companyProfileId: "",
    buildingType,
    workType,
    architect: "",
    projectSF: projectSF || 0,
    zipCode: "",
    divisionTotals: {},
    outcomeMetadata: {},
    ownerId: ownerId || "",
    orgId: orgId || "",
    assignedTo: ownerId ? [ownerId] : [],
    templateId: null,
    correspondenceCount: 0,
    correspondencePendingCount: 0,
    correspondenceNextDue: "",
    correspondenceTotalHours: 0,
    sourceRfpId: "",
    emailCount: 0,
    lastEmailAt: "",
    schedulePauses: [],
    manualPercentComplete: null,
    manualHoursLogged: null,
    delegatedBy: "",
    visibility: "private",
  };

  useEstimatesStore.setState(s => ({
    activeEstimateId: estimateId,
    estimatesIndex: [...s.estimatesIndex, newEntry],
  }));

  // Hydrate project store with metadata
  useProjectStore.getState().setProject({
    name: projectName,
    client: clientName,
    buildingSF: String(projectSF || ""),
    buildingType,
    jobType: buildingType,
    workType,
    laborType: laborType || settings.defaultLaborType || "open_shop",
    location,
    description: "Generated by NOVA Autopilot",
    date: today(),
  });

  // Set default markups
  const defaultMarkup = {
    overhead: 10,
    profit: 10,
    contingency: 5,
    generalConditions: 0,
    insurance: 2,
    tax: 0,
    bond: 0,
  };
  useItemsStore.getState().setMarkup(defaultMarkup);

  onProgress("init", 5, "Estimate environment created");
  checkAbort(signal);

  // ── Phase 2: Load PDF files into drawings store ───────────────────────────
  onProgress("pdf", 10, `Loading ${pdfFiles.length} PDF file(s)...`);

  const { extractDrawingPages } = await import("@/utils/uploadPipeline");
  let totalPages = 0;

  for (let i = 0; i < pdfFiles.length; i++) {
    const file = pdfFiles[i];
    const pct = 10 + ((i + 1) / pdfFiles.length) * 15;
    onProgress("pdf", Math.round(pct), `Processing ${file.name}...`);
    checkAbort(signal);

    try {
      const pageIds = await extractDrawingPages(file);
      totalPages += pageIds.length;
    } catch (err) {
      console.warn(`[autopilot] Failed to load ${file.name}:`, err.message);
      // Non-critical — continue with remaining files
    }
  }

  const drawingCount = useDrawingsStore.getState().drawings.filter(d => d.data).length;
  onProgress("pdf", 25, `${drawingCount} drawing pages loaded`);
  checkAbort(signal);

  // If no drawings were loaded and no PDFs provided, we can still do ROM-only
  if (drawingCount === 0 && pdfFiles.length > 0) {
    console.warn("[autopilot] No drawings loaded from PDFs — falling back to ROM-only");
  }

  // ── Phase 3: Run full scan pipeline ───────────────────────────────────────
  let scanResult = null;

  if (drawingCount > 0) {
    onProgress("scan", 30, "Running NOVA scan pipeline...");

    try {
      scanResult = await new Promise((resolve, reject) => {
        // runFullScan returns results AND calls onComplete
        // It reads drawings from drawingsStore.getState() internally
        import("@/utils/scanRunner").then(({ runFullScan }) => {
          runFullScan({
            onComplete: resolve,
            onError: err => reject(new Error(typeof err === "string" ? err : err?.message || "Scan failed")),
            signal,
          }).then(result => {
            // runFullScan also returns the result directly
            // resolve with whichever arrives first (onComplete fires before return)
            if (result && !scanResult) resolve(result);
          }).catch(reject);
        }).catch(reject);
      });
    } catch (err) {
      if (err instanceof AutopilotAbortError || err.message === "__SCAN_STOPPED__" || signal?.aborted) {
        throw new AutopilotAbortError();
      }
      console.warn("[autopilot] Scan failed, falling back to baseline ROM:", err.message);
    }
  }

  onProgress("scan", 80, "Scan pipeline complete");
  checkAbort(signal);

  // ── Phase 3.5: Knowledge enrichment ──────────────────────────────────────
  // Load firm memory, corrections, similar proposals — all non-critical
  onProgress("knowledge", 81, "Loading NOVA knowledge base...");

  let firmContext = "";
  let firmPatternsApplied = 0;
  let correctionContext = "";
  let correctionPatternsApplied = 0;
  let similarProposals = [];
  let learningStats = { corrections: 0, firmPatterns: 0, proposals: 0 };

  // 1. Firm memory — if we detected an architect/engineer from title block
  try {
    const project = useProjectStore.getState().project || {};
    const firmName = project.architect || project.engineer ||
      scanResult?.titleBlock?.architect || scanResult?.titleBlock?.engineer || "";
    if (firmName) {
      const { useFirmMemoryStore } = await import("@/nova/learning/firmMemory");
      firmContext = useFirmMemoryStore.getState().buildFirmContext(firmName);
      if (firmContext) {
        firmPatternsApplied = (firmContext.match(/^- /gm) || []).length;
        console.log(`[autopilot] Firm memory: ${firmPatternsApplied} patterns applied for "${firmName}"`);
      }
    }
  } catch (err) {
    console.warn("[autopilot] Firm memory load failed:", err.message);
  }

  // 2. Correction context — cross-project correction patterns
  try {
    const { useCorrectionStore } = await import("@/nova/learning/correctionStore");
    correctionContext = useCorrectionStore.getState().buildCorrectionContext();
    if (correctionContext) {
      correctionPatternsApplied = (correctionContext.match(/^- /gm) || []).length;
      console.log(`[autopilot] Corrections: ${correctionPatternsApplied} patterns loaded`);
    }
    const stats = useCorrectionStore.getState().getStats();
    learningStats.corrections = stats.totalCorrections || 0;
  } catch (err) {
    console.warn("[autopilot] Correction context load failed:", err.message);
  }

  // 3. Similar proposals — historical benchmarks via vector search
  try {
    const { searchSimilar } = await import("@/utils/vectorSearch");
    const queryStr = `${buildingType} ${projectSF ? projectSF + " SF" : ""} ${location || ""}`.trim();
    const { results } = await searchSimilar(queryStr, { kinds: ["proposal"], limit: 3 });
    similarProposals = results || [];
    if (similarProposals.length > 0) {
      console.log(`[autopilot] Found ${similarProposals.length} similar proposals for benchmarking`);
    }
  } catch (err) {
    console.warn("[autopilot] Proposal search failed:", err.message);
  }

  // 4. Compute learning stats summary
  try {
    const { useFirmMemoryStore } = await import("@/nova/learning/firmMemory");
    const firms = useFirmMemoryStore.getState().firms || {};
    learningStats.firmPatterns = Object.values(firms).reduce(
      (sum, f) => sum + (f.patterns?.length || 0), 0,
    );
  } catch { /* non-critical */ }

  // Count proposals in benchmark dataset (approximate from vector search availability)
  learningStats.proposals = 85; // known dataset size from historical proposals

  onProgress("knowledge", 82, `Knowledge loaded: ${firmPatternsApplied} firm + ${correctionPatternsApplied} correction patterns`);

  // ── Phase 3b: Generate ROM if scan didn't produce one ─────────────────────
  if (!scanResult?.rom?.totals) {
    onProgress("rom", 82, "Generating baseline ROM...");
    try {
      const { generateBaselineROM, augmentROMWithAI } = await import("@/utils/romEngine");
      const baseline = generateBaselineROM(
        projectSF, buildingType, workType, {}, { laborType, location },
      );
      let rom;
      try {
        rom = await augmentROMWithAI({
          baseline,
          scheduleItems: [],
          projectContext: `${buildingType}, ${projectSF ? projectSF.toLocaleString() : "unknown"} SF, ${location || "unspecified location"}`,
        });
      } catch {
        rom = baseline;
      }
      scanResult = { ...(scanResult || {}), rom };
    } catch (err) {
      console.warn("[autopilot] Baseline ROM generation failed:", err.message);
    }
  }

  // ── Phase 4: Auto-accept scope items into items store ─────────────────────
  onProgress("items", 85, "Populating estimate with scope items...");
  checkAbort(signal);

  // Collect items from scope outline (primary) or raw line items (fallback)
  const scopeItems = scanResult?.scopeOutline?.items || scanResult?.lineItems || [];
  let newItemCount = 0;

  if (scopeItems.length > 0) {
    const newItems = scopeItems.map(item => ({
      id: uid(),
      code: item.code || "",
      description: item.description || "",
      division: item.division || "",
      divisionCode: (item.code || "").split(".")[0]?.padStart(2, "0") || "",
      trade: item.trade || autoTradeFromCode(item.code) || "",
      directive: autoDirective(
        item.material || item.m || 0,
        item.labor || item.l || 0,
        item.equipment || item.e || 0,
        item.subcontractor || item.sub || 0,
      ),
      unit: item.unit || "LS",
      quantity: item.quantity || item.qty || 1,
      material: item.material || item.m || 0,
      labor: item.labor || item.l || 0,
      equipment: item.equipment || item.e || 0,
      subcontractor: item.subcontractor || item.sub || 0,
      source: item.source || "nova-autopilot",
      confidence: item.confidence || 0.7,
      notes: item.notes || "",
      drawingRef: "",
      variables: [],
      formula: "",
      specSection: "",
      specText: "",
      specVariantLabel: "",
      allowanceOf: "",
      allowanceSubMarkup: "",
      locationLocked: false,
      subItems: [],
      bidContext: "base",
    }));

    const existingItems = useItemsStore.getState().items || [];
    useItemsStore.getState().setItems([...existingItems, ...newItems]);
    newItemCount = newItems.length;
  }

  // If we still have no items but have a scope outline generator, try it
  if (newItemCount === 0 && scanResult?.rom) {
    try {
      onProgress("items", 87, "Generating scope outline from ROM...");
      const { generateScopeOutline } = await import("@/utils/scopeOutlineGenerator");
      const outline = await generateScopeOutline({
        scheduleLineItems: scanResult?.lineItems || [],
        rom: scanResult.rom,
        project: {
          projectSF: projectSF,
          buildingType,
          workType,
          laborType,
        },
        notesContext: scanResult?.notesContext || "",
      });

      if (outline?.items?.length > 0) {
        const newItems = outline.items.map(item => ({
          id: uid(),
          code: item.code || "",
          description: item.description || "",
          division: item.division || "",
          divisionCode: (item.code || "").split(".")[0]?.padStart(2, "0") || "",
          trade: item.trade || autoTradeFromCode(item.code) || "",
          directive: autoDirective(
            item.material || 0, item.labor || 0,
            item.equipment || 0, item.subcontractor || 0,
          ),
          unit: item.unit || "LS",
          quantity: item.quantity || 1,
          material: item.material || 0,
          labor: item.labor || 0,
          equipment: item.equipment || 0,
          subcontractor: item.subcontractor || 0,
          source: item.source || "nova-autopilot",
          confidence: item.confidence || 0.6,
          notes: "",
          drawingRef: "",
          variables: [],
          formula: "",
          specSection: "",
          specText: "",
          specVariantLabel: "",
          allowanceOf: "",
          allowanceSubMarkup: "",
          locationLocked: false,
          subItems: [],
          bidContext: "base",
        }));

        useItemsStore.getState().setItems(newItems);
        newItemCount = newItems.length;
      }
    } catch (err) {
      console.warn("[autopilot] Scope outline generation failed:", err.message);
    }
  }

  onProgress("items", 90, `${newItemCount} scope items populated`);

  // ── Phase 5: Compute confidence score ─────────────────────────────────────
  onProgress("score", 95, "Computing quality score...");

  const rom = scanResult?.rom || {};
  const schedules = scanResult?.schedules || [];
  const items = useItemsStore.getState().items || [];
  const project = useProjectStore.getState().project || {};

  const { score: confidenceScore, factors: confidenceFactors } = computeConfidence({
    rom,
    schedules,
    items,
    project,
    drawingNotes: scanResult?.drawingNotes,
    pdfCount: pdfFiles.length,
    drawingCount,
  });

  // ── Phase 6: Persist ──────────────────────────────────────────────────────
  try {
    const { saveEstimate } = await import("@/hooks/usePersistence");
    await saveEstimate();
  } catch (err) {
    console.warn("[autopilot] Post-autopilot save failed:", err.message);
  }

  // ── Result ────────────────────────────────────────────────────────────────
  onProgress("done", 100, "Autopilot complete");

  const elapsed = Date.now() - startTime;

  const result = {
    estimateId,
    projectName,
    buildingType,
    projectSF,
    location,

    // ROM
    rom,
    totalLow: rom?.totals?.low || 0,
    totalMid: rom?.totals?.mid || 0,
    totalHigh: rom?.totals?.high || 0,
    perSF: rom?.totals?.mid && projectSF
      ? Math.round((rom.totals.mid / projectSF) * 100) / 100
      : 0,

    // Items
    itemCount: items.length,
    items,

    // Schedules
    scheduleCount: schedules.length,
    scheduleTypes: schedules.map(s => s.type),

    // Quality
    confidence: confidenceScore,
    confidenceFactors,

    // Meta
    elapsedMs: elapsed,
    elapsedFormatted: elapsed > 60000
      ? `${Math.floor(elapsed / 60000)}m ${Math.round((elapsed % 60000) / 1000)}s`
      : `${Math.round(elapsed / 1000)}s`,

    // Intelligence
    novaIntelligence: scanResult?.novaIntelligence || null,

    // Verification
    verified: rom?._verificationResult?.pass || false,
    verificationIssues: rom?._verificationResult?.issueCount || 0,

    // Knowledge enrichment
    similarProposals,
    learningStats,
    firmContext: firmContext ? true : false,
    correctionContext: correctionContext ? true : false,
    novaKnowledge: {
      knowledgeBaseWords: 41433,
      proposalsInBenchmarks: learningStats.proposals,
      embeddingsSearched: similarProposals.length > 0,
      firmPatternsApplied,
      correctionPatternsApplied,
      similarProposalsFound: similarProposals.length,
      calibrationFactorsUsed: !!(rom?.totals?.mid),
    },
  };

  // Log to evaluation pipeline (non-critical)
  try {
    const { logAICall } = await import("@/nova/learning/evaluationLogger");
    await logAICall({
      phase: "autopilot",
      model: "pipeline",
      inputSummary: `${projectName} | ${buildingType} | ${projectSF}SF | ${pdfFiles.length} PDFs`,
      aiResult: { confidence: confidenceScore, items: items.length, rom: !!rom?.totals },
      latencyMs: elapsed,
    });
  } catch { /* non-critical */ }

  return result;
}

// ═══════════════════════════════════════════════════════════════════════════════
// runQuickAutopilot — ROM-only fast path (no PDF upload)
// For the "Enter Basics" quick estimate flow.
// ═══════════════════════════════════════════════════════════════════════════════
export async function runQuickAutopilot({
  buildingType = "commercial-office",
  projectSF = 10000,
  location = "",
  workType = "new-construction",
  laborType = "open_shop",
  projectName = "Quick Estimate",
} = {}) {
  const { generateBaselineROM, augmentROMWithAI } = await import("@/utils/romEngine");
  const { generateScopeOutline } = await import("@/utils/scopeOutlineGenerator");

  const startTime = Date.now();

  // Generate baseline ROM from benchmark data
  const baseline = generateBaselineROM(
    projectSF, buildingType, workType, {}, { laborType, location },
  );

  // Augment with AI for better accuracy
  let rom;
  try {
    rom = await augmentROMWithAI({
      baseline,
      scheduleItems: [],
      projectContext: `${buildingType}, ${projectSF ? projectSF.toLocaleString() : "unknown"} SF, ${location || "unspecified location"}`,
    });
  } catch {
    rom = baseline;
  }

  // Generate scope outline from ROM alone
  let scopeItems = [];
  try {
    const scope = await generateScopeOutline({
      scheduleLineItems: [],
      rom,
      project: { projectSF, buildingType, workType, laborType },
    });
    scopeItems = scope?.items || [];
  } catch { /* non-critical */ }

  const elapsed = Date.now() - startTime;

  return {
    rom,
    totalLow: rom?.totals?.low || 0,
    totalMid: rom?.totals?.mid || 0,
    totalHigh: rom?.totals?.high || 0,
    perSF: rom?.totals?.mid && projectSF
      ? Math.round((rom.totals.mid / projectSF) * 100) / 100
      : 0,
    itemCount: scopeItems.length,
    items: scopeItems,
    confidence: scopeItems.length > 10 ? 60 : 40,
    elapsedMs: elapsed,
    elapsedFormatted: elapsed > 60000
      ? `${Math.floor(elapsed / 60000)}m ${Math.round((elapsed % 60000) / 1000)}s`
      : `${Math.round(elapsed / 1000)}s`,
  };
}

// ─── Confidence Scoring ──────────────────────────────────────────────────────
function computeConfidence({ rom, schedules, items, project, drawingNotes, pdfCount, drawingCount }) {
  let score = 0;
  const factors = [];

  // Has ROM? (+20)
  if (rom?.totals?.mid > 0) {
    score += 20;
    factors.push("ROM generated");
  }

  // Has schedules? (+15 per type, max 30)
  const schedCount = Math.min((schedules || []).length, 2);
  score += schedCount * 15;
  if (schedCount > 0) {
    factors.push(`${schedules.length} schedule(s) detected`);
  }

  // Has scope items? (+20 if >10, +10 if any)
  if (items.length > 10) {
    score += 20;
    factors.push(`${items.length} scope items`);
  } else if (items.length > 0) {
    score += 10;
    factors.push(`${items.length} scope items (few)`);
  }

  // Had PDFs? (+5)
  if (pdfCount > 0 && drawingCount > 0) {
    score += 5;
    factors.push(`${drawingCount} drawings from ${pdfCount} PDF(s)`);
  }

  // Has drawing notes? (+10)
  if (drawingNotes?.length > 0) {
    const totalNotes = drawingNotes.reduce((s, r) => s + (r.notes?.length || 0), 0);
    if (totalNotes > 0) {
      score += 10;
      factors.push(`${totalNotes} drawing notes extracted`);
    }
  }

  // Has title block info? (+10)
  if (project?.architect || project?.engineer) {
    score += 10;
    factors.push("Title block parsed");
  }

  // ROM verification passed? (+10)
  if (rom?._verificationResult?.pass) {
    score += 10;
    factors.push("ROM verified");
  }

  return { score: Math.min(100, score), factors };
}
